set_pns_commit_mode true
# Starting to commit core rings
create_power_straps  -direction horizontal  -start_at 6.000 -nets VDD -layer M9 -width 6.000 -start_low_ends coordinate  -start_low_ends_coordinate 3.000 -start_high_ends coordinate  -start_high_ends_coordinate 98.472 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction horizontal  -start_at 94.256 -nets VDD -layer M9 -width 6.000 -start_low_ends coordinate  -start_low_ends_coordinate 3.000 -start_high_ends coordinate  -start_high_ends_coordinate 98.472 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction vertical  -start_at 95.472 -nets VDD -layer MRDL -width 6.000 -start_low_ends coordinate  -start_low_ends_coordinate 3.000 -start_high_ends coordinate  -start_high_ends_coordinate 97.256 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction vertical  -start_at 6.000 -nets VDD -layer MRDL -width 6.000 -start_low_ends coordinate  -start_low_ends_coordinate 3.000 -start_high_ends coordinate  -start_high_ends_coordinate 97.256 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction horizontal  -start_at 13.000 -nets VSS -layer M9 -width 6.000 -start_low_ends coordinate  -start_low_ends_coordinate 11.500 -start_high_ends coordinate  -start_high_ends_coordinate 89.972 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction horizontal  -start_at 87.256 -nets VSS -layer M9 -width 6.000 -start_low_ends coordinate  -start_low_ends_coordinate 11.500 -start_high_ends coordinate  -start_high_ends_coordinate 89.972 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction vertical  -start_at 86.972 -nets VSS -layer MRDL -width 6.000 -start_low_ends coordinate  -start_low_ends_coordinate 10.000 -start_high_ends coordinate  -start_high_ends_coordinate 90.256 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction vertical  -start_at 14.500 -nets VSS -layer MRDL -width 6.000 -start_low_ends coordinate  -start_low_ends_coordinate 10.000 -start_high_ends coordinate  -start_high_ends_coordinate 90.256 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
# Starting to commit block rings
# Starting to commit metal8 straps for net VDD
create_power_straps  -direction vertical  -start_at 32.538 -nets VDD  -layer M8 -width 3.000 -pitch_within_group 16.368 -start_low_ends coordinate  -start_low_ends_coordinate 3.000 -start_high_ends coordinate  -start_high_ends_coordinate 97.256 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 48.938 -nets VDD  -layer M8 -width 3.000 -pitch_within_group 16.368 -start_low_ends coordinate  -start_low_ends_coordinate 3.000 -start_high_ends coordinate  -start_high_ends_coordinate 97.256 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 65.338 -nets VDD  -layer M8 -width 3.000 -pitch_within_group 16.368 -start_low_ends coordinate  -start_low_ends_coordinate 3.000 -start_high_ends coordinate  -start_high_ends_coordinate 97.256 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
# Starting to commit metal8 straps for net VSS
create_power_straps  -direction vertical  -start_at 36.170 -nets VSS  -layer M8 -width 3.000 -pitch_within_group 16.368 -start_low_ends coordinate  -start_low_ends_coordinate 9.970 -start_high_ends coordinate  -start_high_ends_coordinate 90.286 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 52.570 -nets VSS  -layer M8 -width 3.000 -pitch_within_group 16.368 -start_low_ends coordinate  -start_low_ends_coordinate 9.970 -start_high_ends coordinate  -start_high_ends_coordinate 90.286 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 68.970 -nets VSS  -layer M8 -width 3.000 -pitch_within_group 16.368 -start_low_ends coordinate  -start_low_ends_coordinate 9.970 -start_high_ends coordinate  -start_high_ends_coordinate 90.286 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
# Starting to commit metal9 straps for net VDD
create_power_straps  -direction horizontal  -start_at 32.360 -nets VDD  -layer M9 -width 3.000 -pitch_within_group 16.064 -start_low_ends coordinate  -start_low_ends_coordinate 3.000 -start_high_ends coordinate  -start_high_ends_coordinate 98.472 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 48.020 -nets VDD  -layer M9 -width 3.000 -pitch_within_group 16.064 -start_low_ends coordinate  -start_low_ends_coordinate 3.000 -start_high_ends coordinate  -start_high_ends_coordinate 98.472 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 63.680 -nets VDD  -layer M9 -width 3.000 -pitch_within_group 16.064 -start_low_ends coordinate  -start_low_ends_coordinate 3.000 -start_high_ends coordinate  -start_high_ends_coordinate 98.472 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
# Starting to commit metal9 straps for net VSS
create_power_straps  -direction horizontal  -start_at 36.360 -nets VSS  -layer M9 -width 3.000 -pitch_within_group 16.064 -start_low_ends coordinate  -start_low_ends_coordinate 11.500 -start_high_ends coordinate  -start_high_ends_coordinate 89.972 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 52.020 -nets VSS  -layer M9 -width 3.000 -pitch_within_group 16.064 -start_low_ends coordinate  -start_low_ends_coordinate 11.500 -start_high_ends coordinate  -start_high_ends_coordinate 89.972 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 67.680 -nets VSS  -layer M9 -width 3.000 -pitch_within_group 16.064 -start_low_ends coordinate  -start_low_ends_coordinate 11.500 -start_high_ends coordinate  -start_high_ends_coordinate 89.972 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
set_pns_commit_mode false
