//****************************************************************************//
// Verilog models generated by SiliconSmart M-2017.03-2 build date: Apr 12, 2017 14:36:58. (SMSC-2) //
// Siliconsmart Path: /cad/synopsys/SiliconSmart/M-2017.03-2/linux64/bin/siliconsmart //
// Host Name: r6cad-tsmc40r.stanford.edu, User Name: akashl, PID: 19180       //
// Directory: /home/akashl/Hybrid-RRAM-NEMS/model/sismart                     //
//                                                                            //
// File generated on Mon Jun 24 06:46:47 PDT 2019. (SMSC-3)                   //
//****************************************************************************//


`timescale 1ns/1ps

module INVX1_test_Y;

  INVX1 instance0(.A(A), .Y(Y));

  INVX1_stim_Y instance1(.A(A), .Y(Y));

endmodule

module INVX1_stim_Y(A, Y);

  output A;
  reg A;
  input Y;

  parameter NUM_INPUT_BITS = 1;
  parameter NUM_OUTPUT_BITS = 1;
  parameter NUM_TOTAL_BITS = NUM_INPUT_BITS + NUM_OUTPUT_BITS;

  parameter OUTPUT_Y_LOCATION = 1;

  parameter NUM_VECTORS = 4;
  reg [0:NUM_TOTAL_BITS-1] vectors [0:NUM_VECTORS-1];
  reg [0:NUM_TOTAL_BITS-1] ivector;
  integer ctr;

  initial begin

    vectors[0] = {1'b0, 1'b1};
    vectors[1] = {1'b1, 1'b0};
    vectors[2] = {1'b1, 1'b0};
    vectors[3] = {1'b0, 1'b1};

    for (ctr=0; ctr < NUM_VECTORS; ctr=ctr+1)
    begin
      ivector = vectors[ctr];
      {A} = ivector[0:NUM_INPUT_BITS-1];
      #20;  
      if(ivector[OUTPUT_Y_LOCATION] !== Y && ivector[OUTPUT_Y_LOCATION] !== 1'bx)
        $display("testbench ERROR : INVX1:Y output mismatch at vector no. %d, %b != %b",
                 ctr, ivector[OUTPUT_Y_LOCATION], Y);
    end

  end

endmodule
