set_pns_commit_mode true
# Starting to commit core rings
create_power_straps  -direction horizontal  -start_at 6.000 -nets VDD -layer M9 -width 6.000 -start_low_ends coordinate  -start_low_ends_coordinate 3.000 -start_high_ends coordinate  -start_high_ends_coordinate 116.864 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction horizontal  -start_at 112.648 -nets VDD -layer M9 -width 6.000 -start_low_ends coordinate  -start_low_ends_coordinate 3.000 -start_high_ends coordinate  -start_high_ends_coordinate 116.864 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction vertical  -start_at 113.864 -nets VDD -layer MRDL -width 6.000 -start_low_ends coordinate  -start_low_ends_coordinate 3.000 -start_high_ends coordinate  -start_high_ends_coordinate 115.648 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction vertical  -start_at 6.000 -nets VDD -layer MRDL -width 6.000 -start_low_ends coordinate  -start_low_ends_coordinate 3.000 -start_high_ends coordinate  -start_high_ends_coordinate 115.648 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction horizontal  -start_at 13.000 -nets VSS -layer M9 -width 6.000 -start_low_ends coordinate  -start_low_ends_coordinate 11.500 -start_high_ends coordinate  -start_high_ends_coordinate 108.364 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction horizontal  -start_at 105.648 -nets VSS -layer M9 -width 6.000 -start_low_ends coordinate  -start_low_ends_coordinate 11.500 -start_high_ends coordinate  -start_high_ends_coordinate 108.364 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction vertical  -start_at 105.364 -nets VSS -layer MRDL -width 6.000 -start_low_ends coordinate  -start_low_ends_coordinate 10.000 -start_high_ends coordinate  -start_high_ends_coordinate 108.648 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction vertical  -start_at 14.500 -nets VSS -layer MRDL -width 6.000 -start_low_ends coordinate  -start_low_ends_coordinate 10.000 -start_high_ends coordinate  -start_high_ends_coordinate 108.648 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
# Starting to commit block rings
# Starting to commit metal8 straps for net VDD
create_power_straps  -direction vertical  -start_at 33.030 -nets VDD  -layer M8 -width 3.000 -pitch_within_group 16.772 -start_low_ends coordinate  -start_low_ends_coordinate 3.000 -start_high_ends coordinate  -start_high_ends_coordinate 115.648 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 49.758 -nets VDD  -layer M8 -width 3.000 -pitch_within_group 16.772 -start_low_ends coordinate  -start_low_ends_coordinate 3.000 -start_high_ends coordinate  -start_high_ends_coordinate 115.648 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 66.486 -nets VDD  -layer M8 -width 3.000 -pitch_within_group 16.772 -start_low_ends coordinate  -start_low_ends_coordinate 3.000 -start_high_ends coordinate  -start_high_ends_coordinate 115.648 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 83.214 -nets VDD  -layer M8 -width 3.000 -pitch_within_group 16.772 -start_low_ends coordinate  -start_low_ends_coordinate 3.000 -start_high_ends coordinate  -start_high_ends_coordinate 115.648 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
# Starting to commit metal8 straps for net VSS
create_power_straps  -direction vertical  -start_at 36.662 -nets VSS  -layer M8 -width 3.000 -pitch_within_group 16.772 -start_low_ends coordinate  -start_low_ends_coordinate 9.970 -start_high_ends coordinate  -start_high_ends_coordinate 108.648 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 53.390 -nets VSS  -layer M8 -width 3.000 -pitch_within_group 16.772 -start_low_ends coordinate  -start_low_ends_coordinate 9.970 -start_high_ends coordinate  -start_high_ends_coordinate 108.648 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 70.118 -nets VSS  -layer M8 -width 3.000 -pitch_within_group 16.772 -start_low_ends coordinate  -start_low_ends_coordinate 9.970 -start_high_ends coordinate  -start_high_ends_coordinate 108.648 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 86.846 -nets VSS  -layer M8 -width 3.000 -pitch_within_group 16.772 -start_low_ends coordinate  -start_low_ends_coordinate 9.970 -start_high_ends coordinate  -start_high_ends_coordinate 108.648 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
# Starting to commit metal9 straps for net VDD
create_power_straps  -direction horizontal  -start_at 32.360 -nets VDD  -layer M9 -width 3.000 -pitch_within_group 16.528 -start_low_ends coordinate  -start_low_ends_coordinate 3.000 -start_high_ends coordinate  -start_high_ends_coordinate 116.864 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 49.760 -nets VDD  -layer M9 -width 3.000 -pitch_within_group 16.528 -start_low_ends coordinate  -start_low_ends_coordinate 3.000 -start_high_ends coordinate  -start_high_ends_coordinate 116.864 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 65.420 -nets VDD  -layer M9 -width 3.000 -pitch_within_group 16.528 -start_low_ends coordinate  -start_low_ends_coordinate 3.000 -start_high_ends coordinate  -start_high_ends_coordinate 116.864 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 82.820 -nets VDD  -layer M9 -width 3.000 -pitch_within_group 16.528 -start_low_ends coordinate  -start_low_ends_coordinate 3.000 -start_high_ends coordinate  -start_high_ends_coordinate 116.864 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
# Starting to commit metal9 straps for net VSS
create_power_straps  -direction horizontal  -start_at 36.360 -nets VSS  -layer M9 -width 3.000 -pitch_within_group 16.528 -start_low_ends coordinate  -start_low_ends_coordinate 11.500 -start_high_ends coordinate  -start_high_ends_coordinate 108.364 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 53.760 -nets VSS  -layer M9 -width 3.000 -pitch_within_group 16.528 -start_low_ends coordinate  -start_low_ends_coordinate 11.500 -start_high_ends coordinate  -start_high_ends_coordinate 108.364 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 69.420 -nets VSS  -layer M9 -width 3.000 -pitch_within_group 16.528 -start_low_ends coordinate  -start_low_ends_coordinate 11.500 -start_high_ends coordinate  -start_high_ends_coordinate 108.364 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 86.820 -nets VSS  -layer M9 -width 3.000 -pitch_within_group 16.528 -start_low_ends coordinate  -start_low_ends_coordinate 11.500 -start_high_ends coordinate  -start_high_ends_coordinate 108.364 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
set_pns_commit_mode false
