set_pns_commit_mode true
# Starting to commit core rings
create_power_straps  -direction horizontal  -start_at 6.000 -nets VDD -layer M9 -width 6.000 -start_low_ends coordinate  -start_low_ends_coordinate 3.000 -start_high_ends coordinate  -start_high_ends_coordinate 176.864 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction horizontal  -start_at 172.648 -nets VDD -layer M9 -width 6.000 -start_low_ends coordinate  -start_low_ends_coordinate 3.000 -start_high_ends coordinate  -start_high_ends_coordinate 176.864 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction vertical  -start_at 173.864 -nets VDD -layer MRDL -width 6.000 -start_low_ends coordinate  -start_low_ends_coordinate 3.000 -start_high_ends coordinate  -start_high_ends_coordinate 175.648 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction vertical  -start_at 6.000 -nets VDD -layer MRDL -width 6.000 -start_low_ends coordinate  -start_low_ends_coordinate 3.000 -start_high_ends coordinate  -start_high_ends_coordinate 175.648 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction horizontal  -start_at 13.000 -nets VSS -layer M9 -width 6.000 -start_low_ends coordinate  -start_low_ends_coordinate 11.500 -start_high_ends coordinate  -start_high_ends_coordinate 168.364 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction horizontal  -start_at 165.648 -nets VSS -layer M9 -width 6.000 -start_low_ends coordinate  -start_low_ends_coordinate 11.500 -start_high_ends coordinate  -start_high_ends_coordinate 168.364 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction vertical  -start_at 165.364 -nets VSS -layer MRDL -width 6.000 -start_low_ends coordinate  -start_low_ends_coordinate 10.000 -start_high_ends coordinate  -start_high_ends_coordinate 168.648 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction vertical  -start_at 14.500 -nets VSS -layer MRDL -width 6.000 -start_low_ends coordinate  -start_low_ends_coordinate 10.000 -start_high_ends coordinate  -start_high_ends_coordinate 168.648 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
# Starting to commit block rings
# Starting to commit metal8 straps for net VDD
create_power_straps  -direction vertical  -start_at 30.558 -nets VDD  -layer M8 -width 3.000 -pitch_within_group 14.386 -start_low_ends coordinate  -start_low_ends_coordinate 3.000 -start_high_ends coordinate  -start_high_ends_coordinate 175.648 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 44.990 -nets VDD  -layer M8 -width 3.000 -pitch_within_group 14.386 -start_low_ends coordinate  -start_low_ends_coordinate 3.000 -start_high_ends coordinate  -start_high_ends_coordinate 175.648 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 59.422 -nets VDD  -layer M8 -width 3.000 -pitch_within_group 14.386 -start_low_ends coordinate  -start_low_ends_coordinate 3.000 -start_high_ends coordinate  -start_high_ends_coordinate 175.648 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 73.690 -nets VDD  -layer M8 -width 3.000 -pitch_within_group 14.386 -start_low_ends coordinate  -start_low_ends_coordinate 3.000 -start_high_ends coordinate  -start_high_ends_coordinate 175.648 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 88.122 -nets VDD  -layer M8 -width 3.000 -pitch_within_group 14.386 -start_low_ends coordinate  -start_low_ends_coordinate 3.000 -start_high_ends coordinate  -start_high_ends_coordinate 175.648 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 102.554 -nets VDD  -layer M8 -width 3.000 -pitch_within_group 14.386 -start_low_ends coordinate  -start_low_ends_coordinate 3.000 -start_high_ends coordinate  -start_high_ends_coordinate 175.648 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 116.822 -nets VDD  -layer M8 -width 3.000 -pitch_within_group 14.386 -start_low_ends coordinate  -start_low_ends_coordinate 3.000 -start_high_ends coordinate  -start_high_ends_coordinate 175.648 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 131.254 -nets VDD  -layer M8 -width 3.000 -pitch_within_group 14.386 -start_low_ends coordinate  -start_low_ends_coordinate 3.000 -start_high_ends coordinate  -start_high_ends_coordinate 175.648 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 145.686 -nets VDD  -layer M8 -width 3.000 -pitch_within_group 14.386 -start_low_ends coordinate  -start_low_ends_coordinate 3.000 -start_high_ends coordinate  -start_high_ends_coordinate 175.648 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
# Starting to commit metal8 straps for net VSS
create_power_straps  -direction vertical  -start_at 34.190 -nets VSS  -layer M8 -width 3.000 -pitch_within_group 14.386 -start_low_ends coordinate  -start_low_ends_coordinate 10.000 -start_high_ends coordinate  -start_high_ends_coordinate 168.648 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 48.622 -nets VSS  -layer M8 -width 3.000 -pitch_within_group 14.386 -start_low_ends coordinate  -start_low_ends_coordinate 10.000 -start_high_ends coordinate  -start_high_ends_coordinate 168.648 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 63.054 -nets VSS  -layer M8 -width 3.000 -pitch_within_group 14.386 -start_low_ends coordinate  -start_low_ends_coordinate 10.000 -start_high_ends coordinate  -start_high_ends_coordinate 168.648 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 77.322 -nets VSS  -layer M8 -width 3.000 -pitch_within_group 14.386 -start_low_ends coordinate  -start_low_ends_coordinate 10.000 -start_high_ends coordinate  -start_high_ends_coordinate 168.648 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 91.754 -nets VSS  -layer M8 -width 3.000 -pitch_within_group 14.386 -start_low_ends coordinate  -start_low_ends_coordinate 10.000 -start_high_ends coordinate  -start_high_ends_coordinate 168.648 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 106.186 -nets VSS  -layer M8 -width 3.000 -pitch_within_group 14.386 -start_low_ends coordinate  -start_low_ends_coordinate 10.000 -start_high_ends coordinate  -start_high_ends_coordinate 168.648 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 120.454 -nets VSS  -layer M8 -width 3.000 -pitch_within_group 14.386 -start_low_ends coordinate  -start_low_ends_coordinate 10.000 -start_high_ends coordinate  -start_high_ends_coordinate 168.648 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 134.886 -nets VSS  -layer M8 -width 3.000 -pitch_within_group 14.386 -start_low_ends coordinate  -start_low_ends_coordinate 10.000 -start_high_ends coordinate  -start_high_ends_coordinate 168.648 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 149.318 -nets VSS  -layer M8 -width 3.000 -pitch_within_group 14.386 -start_low_ends coordinate  -start_low_ends_coordinate 10.000 -start_high_ends coordinate  -start_high_ends_coordinate 168.648 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
# Starting to commit metal9 straps for net VDD
create_power_straps  -direction horizontal  -start_at 31.040 -nets VDD  -layer M9 -width 3.000 -pitch_within_group 14.264 -start_low_ends coordinate  -start_low_ends_coordinate 3.000 -start_high_ends coordinate  -start_high_ends_coordinate 176.864 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 44.960 -nets VDD  -layer M9 -width 3.000 -pitch_within_group 14.264 -start_low_ends coordinate  -start_low_ends_coordinate 3.000 -start_high_ends coordinate  -start_high_ends_coordinate 176.864 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 58.880 -nets VDD  -layer M9 -width 3.000 -pitch_within_group 14.264 -start_low_ends coordinate  -start_low_ends_coordinate 3.000 -start_high_ends coordinate  -start_high_ends_coordinate 176.864 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 72.800 -nets VDD  -layer M9 -width 3.000 -pitch_within_group 14.264 -start_low_ends coordinate  -start_low_ends_coordinate 3.000 -start_high_ends coordinate  -start_high_ends_coordinate 176.864 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 86.720 -nets VDD  -layer M9 -width 3.000 -pitch_within_group 14.264 -start_low_ends coordinate  -start_low_ends_coordinate 3.000 -start_high_ends coordinate  -start_high_ends_coordinate 176.864 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 102.380 -nets VDD  -layer M9 -width 3.000 -pitch_within_group 14.264 -start_low_ends coordinate  -start_low_ends_coordinate 3.000 -start_high_ends coordinate  -start_high_ends_coordinate 176.864 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 116.300 -nets VDD  -layer M9 -width 3.000 -pitch_within_group 14.264 -start_low_ends coordinate  -start_low_ends_coordinate 3.000 -start_high_ends coordinate  -start_high_ends_coordinate 176.864 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 130.220 -nets VDD  -layer M9 -width 3.000 -pitch_within_group 14.264 -start_low_ends coordinate  -start_low_ends_coordinate 3.000 -start_high_ends coordinate  -start_high_ends_coordinate 176.864 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 144.140 -nets VDD  -layer M9 -width 3.000 -pitch_within_group 14.264 -start_low_ends coordinate  -start_low_ends_coordinate 3.000 -start_high_ends coordinate  -start_high_ends_coordinate 176.864 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
# Starting to commit metal9 straps for net VSS
create_power_straps  -direction horizontal  -start_at 35.040 -nets VSS  -layer M9 -width 3.000 -pitch_within_group 14.264 -start_low_ends coordinate  -start_low_ends_coordinate 11.500 -start_high_ends coordinate  -start_high_ends_coordinate 168.364 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 48.960 -nets VSS  -layer M9 -width 3.000 -pitch_within_group 14.264 -start_low_ends coordinate  -start_low_ends_coordinate 11.500 -start_high_ends coordinate  -start_high_ends_coordinate 168.364 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 62.880 -nets VSS  -layer M9 -width 3.000 -pitch_within_group 14.264 -start_low_ends coordinate  -start_low_ends_coordinate 11.500 -start_high_ends coordinate  -start_high_ends_coordinate 168.364 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 76.800 -nets VSS  -layer M9 -width 3.000 -pitch_within_group 14.264 -start_low_ends coordinate  -start_low_ends_coordinate 11.500 -start_high_ends coordinate  -start_high_ends_coordinate 168.364 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 90.720 -nets VSS  -layer M9 -width 3.000 -pitch_within_group 14.264 -start_low_ends coordinate  -start_low_ends_coordinate 11.500 -start_high_ends coordinate  -start_high_ends_coordinate 168.364 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 106.380 -nets VSS  -layer M9 -width 3.000 -pitch_within_group 14.264 -start_low_ends coordinate  -start_low_ends_coordinate 11.500 -start_high_ends coordinate  -start_high_ends_coordinate 168.364 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 120.300 -nets VSS  -layer M9 -width 3.000 -pitch_within_group 14.264 -start_low_ends coordinate  -start_low_ends_coordinate 11.500 -start_high_ends coordinate  -start_high_ends_coordinate 168.364 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 134.220 -nets VSS  -layer M9 -width 3.000 -pitch_within_group 14.264 -start_low_ends coordinate  -start_low_ends_coordinate 11.500 -start_high_ends coordinate  -start_high_ends_coordinate 168.364 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 148.140 -nets VSS  -layer M9 -width 3.000 -pitch_within_group 14.264 -start_low_ends coordinate  -start_low_ends_coordinate 11.500 -start_high_ends coordinate  -start_high_ends_coordinate 168.364 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
set_pns_commit_mode false
