set_pns_commit_mode true
# Starting to commit core rings
create_power_straps  -direction horizontal  -start_at 6.000 -nets VDD -layer M9 -width 6.000 -start_low_ends coordinate  -start_low_ends_coordinate 3.000 -start_high_ends coordinate  -start_high_ends_coordinate 91.328 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction horizontal  -start_at 87.568 -nets VDD -layer M9 -width 6.000 -start_low_ends coordinate  -start_low_ends_coordinate 3.000 -start_high_ends coordinate  -start_high_ends_coordinate 91.328 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction vertical  -start_at 88.328 -nets VDD -layer MRDL -width 6.000 -start_low_ends coordinate  -start_low_ends_coordinate 3.000 -start_high_ends coordinate  -start_high_ends_coordinate 90.568 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction vertical  -start_at 6.000 -nets VDD -layer MRDL -width 6.000 -start_low_ends coordinate  -start_low_ends_coordinate 3.000 -start_high_ends coordinate  -start_high_ends_coordinate 90.568 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction horizontal  -start_at 13.000 -nets VSS -layer M9 -width 6.000 -start_low_ends coordinate  -start_low_ends_coordinate 11.500 -start_high_ends coordinate  -start_high_ends_coordinate 82.828 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction horizontal  -start_at 80.568 -nets VSS -layer M9 -width 6.000 -start_low_ends coordinate  -start_low_ends_coordinate 11.500 -start_high_ends coordinate  -start_high_ends_coordinate 82.828 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction vertical  -start_at 79.828 -nets VSS -layer MRDL -width 6.000 -start_low_ends coordinate  -start_low_ends_coordinate 10.000 -start_high_ends coordinate  -start_high_ends_coordinate 83.568 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction vertical  -start_at 14.500 -nets VSS -layer MRDL -width 6.000 -start_low_ends coordinate  -start_low_ends_coordinate 10.000 -start_high_ends coordinate  -start_high_ends_coordinate 83.568 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
# Starting to commit block rings
# Starting to commit metal8 straps for net VDD
create_power_straps  -direction vertical  -start_at 30.734 -nets VDD  -layer M8 -width 3.000 -pitch_within_group 14.582 -start_low_ends coordinate  -start_low_ends_coordinate 3.000 -start_high_ends coordinate  -start_high_ends_coordinate 90.568 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 45.330 -nets VDD  -layer M8 -width 3.000 -pitch_within_group 14.582 -start_low_ends coordinate  -start_low_ends_coordinate 3.000 -start_high_ends coordinate  -start_high_ends_coordinate 90.568 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 59.926 -nets VDD  -layer M8 -width 3.000 -pitch_within_group 14.582 -start_low_ends coordinate  -start_low_ends_coordinate 3.000 -start_high_ends coordinate  -start_high_ends_coordinate 90.568 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
# Starting to commit metal8 straps for net VSS
create_power_straps  -direction vertical  -start_at 34.366 -nets VSS  -layer M8 -width 3.000 -pitch_within_group 14.582 -start_low_ends coordinate  -start_low_ends_coordinate 9.970 -start_high_ends coordinate  -start_high_ends_coordinate 83.598 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 48.962 -nets VSS  -layer M8 -width 3.000 -pitch_within_group 14.582 -start_low_ends coordinate  -start_low_ends_coordinate 9.970 -start_high_ends coordinate  -start_high_ends_coordinate 83.598 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 63.558 -nets VSS  -layer M8 -width 3.000 -pitch_within_group 14.582 -start_low_ends coordinate  -start_low_ends_coordinate 9.970 -start_high_ends coordinate  -start_high_ends_coordinate 83.598 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
# Starting to commit metal9 straps for net VDD
create_power_straps  -direction horizontal  -start_at 30.620 -nets VDD  -layer M9 -width 3.000 -pitch_within_group 14.392 -start_low_ends coordinate  -start_low_ends_coordinate 3.000 -start_high_ends coordinate  -start_high_ends_coordinate 91.328 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 44.540 -nets VDD  -layer M9 -width 3.000 -pitch_within_group 14.392 -start_low_ends coordinate  -start_low_ends_coordinate 3.000 -start_high_ends coordinate  -start_high_ends_coordinate 91.328 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 58.460 -nets VDD  -layer M9 -width 3.000 -pitch_within_group 14.392 -start_low_ends coordinate  -start_low_ends_coordinate 3.000 -start_high_ends coordinate  -start_high_ends_coordinate 91.328 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
# Starting to commit metal9 straps for net VSS
create_power_straps  -direction horizontal  -start_at 34.620 -nets VSS  -layer M9 -width 3.000 -pitch_within_group 14.392 -start_low_ends coordinate  -start_low_ends_coordinate 11.500 -start_high_ends coordinate  -start_high_ends_coordinate 82.828 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 48.540 -nets VSS  -layer M9 -width 3.000 -pitch_within_group 14.392 -start_low_ends coordinate  -start_low_ends_coordinate 11.500 -start_high_ends coordinate  -start_high_ends_coordinate 82.828 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 62.460 -nets VSS  -layer M9 -width 3.000 -pitch_within_group 14.392 -start_low_ends coordinate  -start_low_ends_coordinate 11.500 -start_high_ends coordinate  -start_high_ends_coordinate 82.828 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
set_pns_commit_mode false
