##############################################################################
# Template generated by SiliconSmart M-2017.03-2 (built on Apr 12, 2017 14:36:58) #
# SiliconSmart Path: /cad/synopsys/SiliconSmart/M-2017.03-2/linux64/bin/siliconsmart #
# Host Name: r6cad-tsmc40r.stanford.edu, User Name: akashl, PID: 19180 #
# Directory: /home/akashl/Hybrid-RRAM-NEMS/model/sismart #
# Date Mon, 24 Jun 2019 06:45:15 PDT #
#                                                                            #
# Copyright (C) 2017 Synopsys Inc.                                #
# This file contains confidential and proprietry information.                #
# All rights reserved.                                                       #
#                                                                            #
##############################################################################

set tempTestColl [ SBTestCollection automap ]


# Specifies the version of the template API expected by this file.
$tempTestColl setTemplateVer 7

## 
## Configuration Flags
$tempTestColl setConfigurationFlags { doTiming doPower doCcs }

## 
## Formal Ports
$tempTestColl makeFormalPorts {A Y}
$tempTestColl setParameter retention_ports {}
$tempTestColl setParameter synch_controls {}
$tempTestColl setParameter clock_ports {}
$tempTestColl setParameter asynch_ports {}
$tempTestColl setParameter asynch_ports_active_state {}

## 
## Tests

## 
## Test capload0__delay__A__lh__Y__hl
set tempTest [ SBTest "capload0__delay__A__lh__Y__hl" ]
$tempTest setTargets { capload__A__lh__Y__hl }
$tempTest setTargetInputs {
  {A lh}}

$tempTest setTargetOutputs {
  {Y hl}}

$tempTest setSwitchingInputs {
  {A lh}}

$tempTest setAnalysisType tranPlus

## 
## Sweep Specification
$tempTest setTagNumTableDimensions 0 mpw

## 
## Harnesses
$tempTest setAcquire 1
$tempTest setStateCoverage "1"

## 
## ACQ_1
set tempAcq [ SBCaploadAcquisition "ACQ_1" ]
$tempAcq setHarnessName default
$tempAcq setAcquire 1
$tempAcq setState "1"
$tempAcq setStateCoverage "1"

## 
## Wavetable
set tempWT [ SBWaveTable ]
$tempWT setInterface { Y:inout A } { initial_delay units ct default_slew opt_load_low opt_load_high max_tout slew_guardband_ratio maxload_tout_resolution }

$tempWT setStimulus         {   A    Y     } {
            "0"          {} {   0    Z,1   }
"initial_delay" { in1 out } {   1    Z,0   }
}

$tempWT addMeasurements {} {
  { tin_A                Tin        { A in1 } NO_USER SYS }
  { delay_A_Y            delay      { A in1 Y out } NO_USER SYS }
  { tout_Y               Tout       { Y out } NO_USER SYS }
}

$tempWT addOptimization    load_Y    opt_load_low    opt_load_high    tout_Y    { delay_A_Y tin_A } {  } {  } {  } non_negative_linear max_tout*slew_guardband_ratio maxload_tout_resolution None None opt_load_low "None"
$tempWT bindInterface { Y A } { cell_initial_delay A[cycle_time] A[cycle_time] A[default_slew] Y[opt_load_low] Y[opt_load_high] Y[max_tout] Y[slew_guardband_ratio] Y[maxload_tout_resolution] }
$tempAcq addWaveTable $tempWT
release_obj $tempWT

## 
## Sweep Specification
$tempAcq setTagNumTableDimensions 0 mpw

## 
## Harnesses

set tempHarness [ SBHarness default ]
set tempTopOp [ SBTopologyOperation ]
$tempTopOp setElement capacitor
$tempTopOp setElementName cap_Y
$tempTopOp setOperation insert
$tempTopOp setNodes {Y Y[logic_low_name]}
$tempTopOp setParam {load_Y}
$tempHarness addTopologyOperation $tempTopOp
release_obj $tempTopOp
$tempAcq addHarness $tempHarness
release_obj $tempHarness

$tempAcq setHarnessName default
$tempTest addAcquisition $tempAcq
release_obj $tempAcq

$tempTestColl addTest $tempTest
release_obj $tempTest

set tempTestColl

