##############################################################################
# Template generated by SiliconSmart M-2017.03-2 (built on Apr 12, 2017 14:36:58) #
# SiliconSmart Path: /cad/synopsys/SiliconSmart/M-2017.03-2/linux64/bin/siliconsmart #
# Host Name: r6cad-tsmc40r.stanford.edu, User Name: akashl, PID: 19180 #
# Directory: /home/akashl/Hybrid-RRAM-NEMS/model/sismart #
# Date Mon, 24 Jun 2019 06:45:15 PDT #
#                                                                            #
# Copyright (C) 2017 Synopsys Inc.                                #
# This file contains confidential and proprietry information.                #
# All rights reserved.                                                       #
#                                                                            #
##############################################################################

set tempTestColl [ SBTestCollection automap ]


# Specifies the version of the template API expected by this file.
$tempTestColl setTemplateVer 7

## 
## Configuration Flags
$tempTestColl setConfigurationFlags { doTiming doPower doCcs }

## 
## Formal Ports
$tempTestColl makeFormalPorts {A Y}
$tempTestColl setParameter retention_ports {}
$tempTestColl setParameter synch_controls {}
$tempTestColl setParameter clock_ports {}
$tempTestColl setParameter asynch_ports {}
$tempTestColl setParameter asynch_ports_active_state {}

## 
## Tests

## 
## Test delay__A__lh__Y__hl
set tempTest [ SBTest "delay__A__lh__Y__hl" ]
$tempTest setTargets { delay__A__lh__Y__hl Cin__A__lh Tout__Y__hl cap_energy__Y__hl ccs_cin1__A__lh ccs_cin2__A__lh ccs_tin1__A__lh ccs_tin2__A__lh delay_ccs_native_current__A__lh__Y__hl energy1__A__lh__Y__hl__gnd energy1__A__lh__Y__hl__vb energy1__A__lh__Y__hl__vdd energy__A__lh__Y__hl leakage_power1__gnd leakage_power1__vb leakage_power1__vdd leakage_power2__gnd leakage_power2__vb leakage_power2__vdd time_at_voltage__A__lh }
$tempTest setTargetInputs {
  {A lh}}

$tempTest setTargetOutputs {
  {Y hl}}

$tempTest setSwitchingInputs {
  {A lh}}

$tempTest setAnalysisType tranPlus

## 
## Sweep Specification
$tempTest setTagNumTableDimensions 0 mpw

## 
## Harnesses
$tempTest setAcquire 1
$tempTest setParameter dependencies {capload0__delay__A__lh__Y__hl}
$tempTest setStateCoverage "1"

## 
## ACQ_1
set tempAcq [ SBDelayAcquisition "ACQ_1" ]
$tempAcq setHarnessName default
$tempAcq setAcquire 1
$tempAcq setState "1"
$tempAcq setStateCoverage "1"
$tempAcq setAdditionalStateCoverage "1" "energy__A__lh__Y__hl"
$tempAcq setAdditionalStateCoverage "1" "leakage_power2__gnd"
$tempAcq setAdditionalStateCoverage "1" "energy1__A__lh__Y__hl__vb"
$tempAcq setAdditionalStateCoverage "1" "leakage_power1__vb"
$tempAcq setAdditionalStateCoverage "1" "energy1__A__lh__Y__hl__vdd"
$tempAcq setAdditionalStateCoverage "1" "leakage_power1__gnd"
$tempAcq setAdditionalStateCoverage "1" "leakage_power1__vdd"
$tempAcq setAdditionalStateCoverage "1" "cap_energy__Y__hl"
$tempAcq setAdditionalStateCoverage "1" "leakage_power2__vb"
$tempAcq setAdditionalStateCoverage "1" "energy1__A__lh__Y__hl__gnd"
$tempAcq setAdditionalStateCoverage "1" "leakage_power2__vdd"

## 
## Wavetable
set tempWT [ SBWaveTable ]
$tempWT setInterface { Y:inout A } { initial_delay units ct default_slew pp prop_delay_level ccsPoints volt_tolerance stable energy_change_threshold energy_change_abs_threshold }

$tempWT setStimulus                                                {   A    Y     } {
                                                 "0"            {} {   0    Z,1   }
                                     "initial_delay" { start out } {   1    Z,0   }
"max((initial_delay)+(pp),(initial_delay)+(stable))"            {} {   -    -,-   }
}

$tempWT addMeasurements {} {
  { tin_A                Tin        { A start } NO_USER SYS }
  { cin_A                Cin        { A start } NO_USER SYS }
  { ccs_cin1_A           ccs_cin1   { A start } NO_USER SYS }
  { ccs_cin2_A           ccs_cin2   { A start } NO_USER SYS }
  { ccs_tin1_A           ccs_tin1   { A start } NO_USER SYS }
  { ccs_tin2_A           ccs_tin2   { A start } NO_USER SYS }
  { ccs_time_ref_A       time_at_voltage { A prop_delay_level*(__param_VDD-__param_GND)+__param_GND start } NO_USER SYS }
  { tout_Y               Tout       { Y out } NO_USER SYS }
  { delay_A_Y            delay      { A start Y out } NO_USER SYS }
  { delay_ccs_native_current__A__lh__Y__hl delay_ccs_native_current { A start Y gnd out (initial_delay)+(stable) load_Y __param_VDD __param_GND ccsPoints volt_tolerance } NO_USER SYS }
  { energy__A__lh__Y__hl energy     { start pp energy_change_threshold energy_change_abs_threshold 0 } NO_USER SYS }
  { energy1__A__lh__Y__hl__vdd energy1    { start pp energy_change_threshold energy_change_abs_threshold 0 vdd } }
  { leakage_power1__vdd  leakage_power1 { initial_delay+0.95*pp initial_delay+pp vdd } }
  { leakage_power2__vdd  leakage_power2 { initial_delay+0.90*pp initial_delay+0.95*pp vdd } }
  { energy1__A__lh__Y__hl__vb energy1    { start pp energy_change_threshold energy_change_abs_threshold 0 vb } }
  { leakage_power1__vb   leakage_power1 { initial_delay+0.95*pp initial_delay+pp vb } }
  { leakage_power2__vb   leakage_power2 { initial_delay+0.90*pp initial_delay+0.95*pp vb } }
  { energy1__A__lh__Y__hl__gnd energy1    { start pp energy_change_threshold energy_change_abs_threshold 0 gnd } }
  { leakage_power1__gnd  leakage_power1 { initial_delay+0.95*pp initial_delay+pp gnd } }
  { leakage_power2__gnd  leakage_power2 { initial_delay+0.90*pp initial_delay+0.95*pp gnd } }
  { cap_energy__Y__hl    cap_energy { start pp cap_Y Y 0 } }
}

$tempWT bindInterface { Y A } { 10e-12 A[cycle_time] A[cycle_time] A[default_slew] cell_power_period A[prop_delay_inp_level_rise] Y[num_ccs_samples] Y[ccs_max_voltage_error] Y[stable_time] power_stabilization_threshold power_stabilization_threshold_absolute }
$tempAcq addWaveTable $tempWT
release_obj $tempWT

## 
## Sweep Specification
$tempAcq setTagNumTableDimensions 0 mpw

## 
## Harnesses

set tempHarness [ SBHarness default ]
set tempTopOp [ SBTopologyOperation ]
$tempTopOp setElement dcvs
$tempTopOp setElementName cap_ground_Y
$tempTopOp setOperation insert
$tempTopOp setNodes {ground_Y 0}
$tempTopOp setParam {0}
$tempHarness addTopologyOperation $tempTopOp
release_obj $tempTopOp
set tempTopOp [ SBTopologyOperation ]
$tempTopOp setElement capacitor
$tempTopOp setElementName cap_Y
$tempTopOp setOperation insert
$tempTopOp setNodes {Y ground_Y}
$tempTopOp setParam {load_Y}
$tempHarness addTopologyOperation $tempTopOp
release_obj $tempTopOp
$tempAcq addHarness $tempHarness
release_obj $tempHarness

$tempAcq setHarnessName default
$tempTest addAcquisition $tempAcq
release_obj $tempAcq

$tempTestColl addTest $tempTest
release_obj $tempTest

set tempTestColl

