;********************************
; CONTROLS
;********************************
controls(
 techVersion("0.1")

 techParams(
 ;( parameter           value             )
 ;( ----------          -----             )
  ( maskGrid       	0.001 )
  ( cadGrid        	0.001 )
  ( drcGrid        	0.001 )
  ( mfgGrid        	0.001 )
  ( scale          	1.0 )
  ( MPPS           	"(list ( list nil ( quote cwW ) 0.09 ( quote cwL ) 0.09 ( quote cwSp ) 0.10 ( quote cwRowSp ) 0.15 ( quote Cw ) \"CO\" ( quote M1 ) \"M1\" ( quote M1CwEnc ) 0.005 ) ( list nil ( quote name ) \"NWELL\" ( quote pathLayer ) \"DIFF\" ( quote pathWidth ) 0.09 ( quote pathCwEnc ) 0.05 ( quote enclosureLayers ) ( list ) ( quote spacings ) ( list nil ) ) ( list nil ( quote name ) \"sub\" ( quote pathLayer ) \"DIFF\" ( quote pathWidth ) 0.09 ( quote pathCwEnc ) 0.05 ( quote enclosureLayers ) ( list ) ( quote spacings ) ( list nil ) ) )" )
 ) ;techParams

 viewTypeUnits(
 ;( viewType            userUnit       dbuperuu           )
 ;( --------            --------       --------           )
  ( maskLayout     	"micron"       	1000            )
  ( schematic      	"inch"         	160             )
  ( schematicSymbol	"inch"         	160             )
  ( netlist        	"inch"         	160             )
 ) ;viewTypeUnits

 mfgGridResolution(
      ( 0.001000 )
 ) ;mfgGridResolution

) ;controls


;********************************
; LAYER DEFINITION
;********************************
layerDefinitions(

 techPurposes(
 ;( PurposeName               Purpose#   Abbreviation )
 ;( -----------               --------   ------------ )
 ;User-Defined Purposes:
  ( dmy1                      1          dmy1         )
  ( dmy2                      2          dmy2         )
  ( dmy3                      3          dmy3         )
  ( dmy4                      4          dmy4         )
  ( waterMark                 63         waterMark    )
  ( dummy                     127        dummy        )
  ( rram                      5          rram         )
  ( nem                       6          nem          )
 ;System-Reserved Purposes:
  ( text                      220        text         )
  ( subnode                   221        subnode      )
  ( extract                   222        extract      )
 ) ;techPurposes

 techLayers(
 ;( LayerName                 Layer#     Abbreviation )
 ;( ---------                 ------     ------------ )
 ;User-Defined Layers:
  ( NWELL                     1          NWELL        )
  ( DNW                       2          DNW          )
  ( DIFF                      3          DIFF         )
  ( PIMP                      4          PIMP         )
  ( NIMP                      5          NIMP         )
  ( DIFF_18                   6          DIFF_18      )
  ( PAD                       7          PAD          )
  ( ESD_25                    8          ESD_25       )
  ( SBLK                      9          SBLK         )
  ( PO                        10         PO           )
  ( M1                        11         M1           )
  ( VIA1                      12         VIA1         )
  ( M2                        13         M2           )
  ( VIA2                      14         VIA2         )
  ( M3                        15         M3           )
  ( VIA3                      16         VIA3         )
  ( M4                        17         M4           )
  ( VIA4                      18         VIA4         )
  ( M5                        19         M5           )
  ( VIA5                      20         VIA5         )
  ( M6                        21         M6           )
  ( VIA6                      22         VIA6         )
  ( M7                        23         M7           )
  ( VIA7                      24         VIA7         )
  ( M8                        25         M8           )
  ( RRAM                      79         RRAM         )
  ( VIA8                      26         VIA8         )
  ( M9                        27         M9           )
  ( NEMCONT                   80         NEMCONT      )
  ( NEMDIMP                   81         NEMDIMP      )
  ( NEMANC                    82         NEMANC       )
  ( NEMCHAN                   83         NEMCHAN      )
  ( NEMBEAM                   84         NEMBEAM      )
  ( CO                        28         CO           )
  ( HVTIMP                    29         HVTIMP       )
  ( LVTIMP                    30         LVTIMP       )
  ( M1PIN                     31         M1PIN        )
  ( M2PIN                     32         M2PIN        )
  ( M3PIN                     33         M3PIN        )
  ( M4PIN                     34         M4PIN        )
  ( M5PIN                     35         M5PIN        )
  ( M6PIN                     36         M6PIN        )
  ( M7PIN                     37         M7PIN        )
  ( M8PIN                     38         M8PIN        )
  ( M9PIN                     39         M9PIN        )
  ( MRDL                      41         MRDL         )
  ( VIARDL                    42         VIARDL       )
  ( MRPIN                     43         MRPIN        )
  ( HOTNWL                    44         HOTNWL       )
  ( DIOD                      46         DIOD         )
  ( BJTMY                     47         BJTMY        )
  ( RNW                       48         RNW          )
  ( RMARK                     49         RMARK        )
  ( PrBoundary                50         PrBoundary   )
  ( LOGO                      51         LOGO         )
  ( IP                        52         IP           )
  ( RM1                       53         RM1          )
  ( RM2                       54         RM2          )
  ( RM3                       55         RM3          )
  ( RM4                       56         RM4          )
  ( RM5                       57         RM5          )
  ( RM6                       58         RM6          )
  ( RM7                       59         RM7          )
  ( RM8                       60         RM8          )
  ( RM9                       61         RM9          )
  ( DM1EXCL                   64         DM1EXCL      )
  ( DM2EXCL                   65         DM2EXCL      )
  ( DM3EXCL                   66         DM3EXCL      )
  ( DM4EXCL                   67         DM4EXCL      )
  ( DM5EXCL                   68         DM5EXCL      )
  ( DM6EXCL                   69         DM6EXCL      )
  ( DM7EXCL                   70         DM7EXCL      )
  ( DM8EXCL                   71         DM8EXCL      )
  ( DM9EXCL                   72         DM9EXCL      )
  ( DIFFEXCL                  73         DIFFEXCL     )
  ( POEXCL                    74         POEXCL       )
  ( DIFF_25                   75         DIFF_25      )
  ( CBMMARK                   76         CBMMARK      )
  ( CTMMARK                   77         CTMMARK      )
  ( METDMY                    78         METDMY       )
 ) ;techLayers

 techLayerPurposePriorities(
 ;layers are ordered from lowest to highest priority
 ;( LayerName                 Purpose    )
 ;( ---------                 -------    )
  ( background                drawing    )
  ( grid                      drawing    )
  ( grid                      drawing1   )
  ( annotate                  drawing    )
  ( annotate                  drawing1   )
  ( annotate                  drawing2   )
  ( annotate                  drawing3   )
  ( annotate                  drawing4   )
  ( annotate                  drawing5   )
  ( annotate                  drawing6   )
  ( annotate                  drawing7   )
  ( annotate                  drawing8   )
  ( annotate                  drawing9   )
  ( instance                  drawing    )
  ( instance                  label      )
  ( prBoundary                drawing    )
  ( prBoundary                boundary   )
  ( prBoundary                label      )
  ( align                     drawing    )
  ( hardFence                 drawing    )
  ( softFence                 drawing    )
  ( text                      drawing    )
  ( text                      drawing1   )
  ( text                      drawing2   )
  ( border                    drawing    )
  ( device                    drawing    )
  ( device                    label      )
  ( device                    drawing1   )
  ( device                    drawing2   )
  ( device                    annotate   )
  ( wire                      drawing    )
  ( wire                      label      )
  ( wire                      flight     )
  ( pin                       label      )
  ( pin                       drawing    )
  ( pin                       annotate   )
  ( axis                      drawing    )
  ( edgeLayer                 drawing    )
  ( edgeLayer                 pin        )
  ( snap                      boundary   )
  ( snap                      drawing    )
  ( stretch                   drawing    )
  ( y0                        drawing    )
  ( y1                        drawing    )
  ( y2                        drawing    )
  ( y3                        drawing    )
  ( y4                        drawing    )
  ( y5                        drawing    )
  ( y6                        drawing    )
  ( y7                        drawing    )
  ( y8                        drawing    )
  ( y9                        drawing    )
  ( hilite                    drawing    )
  ( hilite                    drawing1   )
  ( hilite                    drawing2   )
  ( hilite                    drawing3   )
  ( hilite                    drawing4   )
  ( hilite                    drawing5   )
  ( hilite                    drawing6   )
  ( hilite                    drawing7   )
  ( hilite                    drawing8   )
  ( hilite                    drawing9   )
  ( select                    drawing    )
  ( drive                     drawing    )
  ( hiz                       drawing    )
  ( resist                    drawing    )
  ( spike                     drawing    )
  ( supply                    drawing    )
  ( unknown                   drawing    )
  ( unset                     drawing    )
  ( designFlow                drawing    )
  ( designFlow                drawing1   )
  ( designFlow                drawing2   )
  ( designFlow                drawing3   )
  ( designFlow                drawing4   )
  ( designFlow                drawing5   )
  ( designFlow                drawing6   )
  ( designFlow                drawing7   )
  ( designFlow                drawing8   )
  ( designFlow                drawing9   )
  ( changedLayer              tool0      )
  ( changedLayer              tool1      )
  ( marker                    warning    )
  ( marker                    error      )
  ( Row                       drawing    )
  ( Row                       label      )
  ( Group                     drawing    )
  ( Group                     label      )
  ( Cannotoccupy              drawing    )
  ( Cannotoccupy              boundary   )
  ( Canplace                  drawing    )
  ( Unrouted                  drawing    )
  ( Unrouted                  drawing1   )
  ( Unrouted                  drawing2   )
  ( Unrouted                  drawing3   )
  ( Unrouted                  drawing4   )
  ( Unrouted                  drawing5   )
  ( Unrouted                  drawing6   )
  ( Unrouted                  drawing7   )
  ( Unrouted                  drawing8   )
  ( Unrouted                  drawing9   )
  ( Row                       boundary   )
  ( Unrouted                  track      )
  ( marker                    annotate   )
  ( marker                    info       )
  ( marker                    ackWarn    )
  ( marker                    soError    )
  ( marker                    soCritical )
  ( marker                    critical   )
  ( marker                    fatal      )
  ( Group                     boundary   )
  ( y0                        flight     )
  ( y1                        flight     )
  ( y2                        flight     )
  ( y3                        flight     )
  ( y4                        flight     )
  ( y5                        flight     )
  ( y6                        flight     )
  ( y7                        flight     )
  ( y8                        flight     )
  ( y9                        flight     )
  ( border                    boundary   )
  ( snap                      grid       )
  ( NWELL                     drawing    )
  ( DNW                       drawing    )
  ( DIFF                      drawing    )
  ( PIMP                      drawing    )
  ( NIMP                      drawing    )
  ( DIFF_18                   drawing    )
  ( PAD                       drawing    )
  ( ESD_25                    drawing    )
  ( SBLK                      drawing    )
  ( PO                        drawing    )
  ( M1                        drawing    )
  ( M1                        track      )
  ( M1                        grid       )
  ( M1                        blockage   )
  ( M2                        drawing    )
  ( M2                        track      )
  ( M2                        grid       )
  ( M2                        blockage   )
  ( M3                        drawing    )
  ( M3                        track      )
  ( M3                        grid       )
  ( M3                        blockage   )
  ( M4                        drawing    )
  ( M4                        track      )
  ( M4                        grid       )
  ( M4                        blockage   )
  ( M5                        drawing    )
  ( M5                        track      )
  ( M5                        grid       )
  ( M5                        blockage   )
  ( M6                        drawing    )
  ( M6                        track      )
  ( M6                        grid       )
  ( M6                        blockage   )
  ( M7                        drawing    )
  ( M7                        track      )
  ( M7                        grid       )
  ( M7                        blockage   )
  ( M8                        drawing    )
  ( M8                        track      )
  ( M8                        grid       )
  ( M8                        blockage   )
  ( RRAM                      drawing    )
  ( RRAM                      track      )
  ( RRAM                      grid       )
  ( RRAM                      blockage   )
  ( M9                        drawing    )
  ( M9                        track      )
  ( M9                        grid       )
  ( M9                        blockage   )
  ( NEMCONT                   drawing    )
  ( NEMCONT                   track      )
  ( NEMCONT                   grid       )
  ( NEMCONT                   blockage   )
  ( NEMDIMP                   drawing    )
  ( NEMDIMP                   track      )
  ( NEMDIMP                   grid       )
  ( NEMDIMP                   blockage   )
  ( NEMANC                    drawing    )
  ( NEMANC                    track      )
  ( NEMANC                    grid       )
  ( NEMANC                    blockage   )
  ( NEMCHAN                   drawing    )
  ( NEMCHAN                   track      )
  ( NEMCHAN                   grid       )
  ( NEMCHAN                   blockage   )
  ( NEMBEAM                   drawing    )
  ( NEMBEAM                   track      )
  ( NEMBEAM                   grid       )
  ( NEMBEAM                   blockage   )
  ( CO                        drawing    )
  ( CO                        grid       )
  ( CO                        blockage   )
  ( VIA1                      drawing    )
  ( VIA1                      grid       )
  ( VIA1                      blockage   )
  ( VIA2                      drawing    )
  ( VIA2                      grid       )
  ( VIA2                      blockage   )
  ( VIA3                      drawing    )
  ( VIA3                      grid       )
  ( VIA3                      blockage   )
  ( VIA4                      drawing    )
  ( VIA4                      grid       )
  ( VIA4                      blockage   )
  ( VIA5                      drawing    )
  ( VIA5                      grid       )
  ( VIA5                      blockage   )
  ( VIA6                      drawing    )
  ( VIA6                      grid       )
  ( VIA6                      blockage   )
  ( VIA7                      drawing    )
  ( VIA7                      grid       )
  ( VIA7                      blockage   )
  ( VIA8                      drawing    )
  ( VIA8                      grid       )
  ( VIA8                      blockage   )
  ( HVTIMP                    drawing    )
  ( LVTIMP                    drawing    )
  ( M1                        text       )
  ( M2                        text       )
  ( M3                        text       )
  ( M4                        text       )
  ( M5                        text       )
  ( M6                        text       )
  ( M7                        text       )
  ( M8                        text       )
  ( M9                        text       )
  ( M1PIN                     drawing    )
  ( M2PIN                     drawing    )
  ( M3PIN                     drawing    )
  ( M4PIN                     drawing    )
  ( M5PIN                     drawing    )
  ( M6PIN                     drawing    )
  ( M7PIN                     drawing    )
  ( M8PIN                     drawing    )
  ( M9PIN                     drawing    )
  ( MRDL                      drawing    )
  ( MRDL                      track      )
  ( MRDL                      grid       )
  ( MRDL                      blockage   )
  ( VIARDL                    drawing    )
  ( VIARDL                    grid       )
  ( VIARDL                    blockage   )
  ( MRPIN                     drawing    )
  ( HOTNWL                    drawing    )
  ( DIOD                      drawing    )
  ( BJTMY                     drawing    )
  ( RNW                       drawing    )
  ( RMARK                     drawing    )
  ( LOGO                      drawing    )
  ( IP                        drawing    )
  ( PrBoundary                drawing    )
  ( RM1                       drawing    )
  ( RM2                       drawing    )
  ( RM3                       drawing    )
  ( RM4                       drawing    )
  ( RM5                       drawing    )
  ( RM6                       drawing    )
  ( RM7                       drawing    )
  ( RM8                       drawing    )
  ( RM9                       drawing    )
  ( DM1EXCL                   drawing    )
  ( DM2EXCL                   drawing    )
  ( DM3EXCL                   drawing    )
  ( DM4EXCL                   drawing    )
  ( DM5EXCL                   drawing    )
  ( DM6EXCL                   drawing    )
  ( DM7EXCL                   drawing    )
  ( DM8EXCL                   drawing    )
  ( DM9EXCL                   drawing    )
  ( DIFFEXCL                  drawing    )
  ( POEXCL                    drawing    )
  ( DIFF_25                   drawing    )
  ( CBMMARK                   drawing    )
  ( CTMMARK                   drawing    )
  ( METDMY                    drawing    )
 ) ;techLayerPurposePriorities

 techDisplays(
 ;( LayerName    Purpose      Packet          Vis Sel Con2ChgLy DrgEnbl Valid )
 ;( ---------    -------      ------          --- --- --------- ------- ----- )
  ( background   drawing      background       t nil t nil nil )
  ( grid         drawing      grid             t nil t nil nil )
  ( grid         drawing1     grid1            t nil t nil nil )
  ( annotate     drawing      annotate         t t t t nil )
  ( annotate     drawing1     annotate1        t t t t nil )
  ( annotate     drawing2     annotate2        t t t t nil )
  ( annotate     drawing3     annotate3        t t t t nil )
  ( annotate     drawing4     annotate4        t t t t nil )
  ( annotate     drawing5     annotate5        t t t t nil )
  ( annotate     drawing6     annotate6        t t t t nil )
  ( annotate     drawing7     annotate7        t t t t nil )
  ( annotate     drawing8     annotate8        t t t t nil )
  ( annotate     drawing9     annotate9        t t t t nil )
  ( instance     drawing      instance         t t t t nil )
  ( instance     label        instanceLbl      t t t t nil )
  ( prBoundary   drawing      prBoundary       t t t t nil )
  ( prBoundary   boundary     prBoundaryBnd    t nil t t nil )
  ( prBoundary   label        prBoundaryLbl    t t t t nil )
  ( align        drawing      defaultPacket    t t t t nil )
  ( hardFence    drawing      hardFence        t t t t nil )
  ( softFence    drawing      softFence        t t t t nil )
  ( text         drawing      text             t t t t nil )
  ( text         drawing1     text1            t t t t nil )
  ( text         drawing2     text2            t t t t nil )
  ( border       drawing      border           t t t t nil )
  ( device       drawing      device           t t t t nil )
  ( device       label        deviceLbl        t t t t nil )
  ( device       drawing1     device1          t t t t nil )
  ( device       drawing2     device2          t t t t nil )
  ( device       annotate     deviceAnt        t t t t nil )
  ( wire         drawing      wire             t t t t nil )
  ( wire         label        wireLbl          t t t t nil )
  ( wire         flight       wireFlt          t t t t nil )
  ( pin          label        pinLbl           t t t t nil )
  ( pin          drawing      pin              t t t t nil )
  ( pin          annotate     pinAnt           t t t t nil )
  ( axis         drawing      axis             t nil t t nil )
  ( edgeLayer    drawing      edgeLayer        t t t t nil )
  ( edgeLayer    pin          edgeLayerPin     t t t t nil )
  ( snap         boundary     snap             t nil t t nil )
  ( snap         drawing      snap             t t t t nil )
  ( stretch      drawing      stretch          t t t t nil )
  ( y0           drawing      y0               t t t t nil )
  ( y1           drawing      y1               t t t t nil )
  ( y2           drawing      y2               t t t t nil )
  ( y3           drawing      y3               t t t t nil )
  ( y4           drawing      y4               t t t t nil )
  ( y5           drawing      y5               t t t t nil )
  ( y6           drawing      y6               t t t t nil )
  ( y7           drawing      y7               t t t t nil )
  ( y8           drawing      y8               t t t t nil )
  ( y9           drawing      y9               t t t t nil )
  ( hilite       drawing      hilite           t t t t nil )
  ( hilite       drawing1     hilite1          t t t t nil )
  ( hilite       drawing2     hilite2          t t t t nil )
  ( hilite       drawing3     hilite3          t t t t nil )
  ( hilite       drawing4     hilite4          t t t t nil )
  ( hilite       drawing5     hilite5          t t t t nil )
  ( hilite       drawing6     hilite6          t t t t nil )
  ( hilite       drawing7     hilite7          t t t t nil )
  ( hilite       drawing8     hilite8          t t t t nil )
  ( hilite       drawing9     hilite9          t t t t nil )
  ( select       drawing      select           t t t t nil )
  ( drive        drawing      drive            t t t t nil )
  ( hiz          drawing      hiz              t t t t nil )
  ( resist       drawing      resist           t t t t nil )
  ( spike        drawing      spike            t t t t nil )
  ( supply       drawing      supply           t t t t nil )
  ( unknown      drawing      unknown          t t t t nil )
  ( unset        drawing      unset            t t t t nil )
  ( designFlow   drawing      designFlow       t nil nil nil nil )
  ( designFlow   drawing1     designFlow1      t nil nil nil nil )
  ( designFlow   drawing2     designFlow2      t nil nil nil nil )
  ( designFlow   drawing3     designFlow3      t nil nil nil nil )
  ( designFlow   drawing4     designFlow4      t nil nil nil nil )
  ( designFlow   drawing5     designFlow5      t nil nil nil nil )
  ( designFlow   drawing6     designFlow6      t nil nil nil nil )
  ( designFlow   drawing7     designFlow7      t nil nil nil nil )
  ( designFlow   drawing8     designFlow8      t nil nil nil nil )
  ( designFlow   drawing9     designFlow9      t nil nil nil nil )
  ( changedLayer tool0        changedLayerTl0  nil nil t nil nil )
  ( changedLayer tool1        changedLayerTl1  nil nil t nil nil )
  ( marker       warning      markerWarn       t t t t nil )
  ( marker       error        markerErr        t t t t nil )
  ( Row          drawing      Row              t t t t nil )
  ( Row          label        RowLbl           t t t t nil )
  ( Group        drawing      Group            t t t t nil )
  ( Group        label        GroupLbl         t t t t nil )
  ( Cannotoccupy drawing      Cannotoccupy     t t t t nil )
  ( Cannotoccupy boundary     CannotoccupyBnd  t t t t nil )
  ( Canplace     drawing      Canplace         t t t t nil )
  ( Unrouted     drawing      Unrouted         t t t t nil )
  ( Unrouted     drawing1     Unrouted1        t t t t nil )
  ( Unrouted     drawing2     Unrouted2        t t t t nil )
  ( Unrouted     drawing3     Unrouted3        t t t t nil )
  ( Unrouted     drawing4     Unrouted4        t t t t nil )
  ( Unrouted     drawing5     Unrouted5        t t t t nil )
  ( Unrouted     drawing6     Unrouted6        t t t t nil )
  ( Unrouted     drawing7     Unrouted7        t t t t nil )
  ( Unrouted     drawing8     Unrouted8        t t t t nil )
  ( Unrouted     drawing9     Unrouted9        t t t t nil )
  ( Row          boundary     RowBnd           t t t t nil )
  ( Unrouted     track        UnroutedTrk      t t t t nil )
  ( marker       annotate     markerAno        t t t t nil )
  ( marker       info         markerInf        t t t t nil )
  ( marker       ackWarn      markerAck        t t t t nil )
  ( marker       soError      markerSer        t t t t nil )
  ( marker       soCritical   markerScr        t t t t nil )
  ( marker       critical     markerCrt        t t t t nil )
  ( marker       fatal        markerFat        t t t t nil )
  ( Group        boundary     GroupBnd         t nil t t nil )
  ( y0           flight       y0Flt            t t t t nil )
  ( y1           flight       y1Flt            t t t t nil )
  ( y2           flight       y2Flt            t t t t nil )
  ( y3           flight       y3Flt            t t t t nil )
  ( y4           flight       y4Flt            t t t t nil )
  ( y5           flight       y5Flt            t t t t nil )
  ( y6           flight       y6Flt            t t t t nil )
  ( y7           flight       y7Flt            t t t t nil )
  ( y8           flight       y8Flt            t t t t nil )
  ( y9           flight       y9Flt            t t t t nil )
  ( border       boundary     area             t nil t t nil )
  ( snap         grid         snap             t nil t nil nil )
  ( NWELL        drawing      NWELL            t t nil nil t )
  ( DNW          drawing      DNW              t t nil nil t )
  ( DIFF         drawing      DIFF             t t nil nil t )
  ( PIMP         drawing      PIMP             t t nil nil t )
  ( NIMP         drawing      NIMP             t t nil nil t )
  ( DIFF_18      drawing      DIFF_18          t t nil nil t )
  ( PAD          drawing      PAD              t t nil nil t )
  ( ESD_25       drawing      ESD_25           t t nil nil t )
  ( SBLK         drawing      SBLK             t t nil nil t )
  ( PO           drawing      PO               t t nil nil t )
  ( M1           drawing      M1               t t nil nil t )
  ( M1           track        M1               nil nil t t nil )
  ( M1           grid         M1               t nil nil nil nil )
  ( M1           blockage     M1               t nil t t nil )
  ( M2           drawing      M2               t t nil nil t )
  ( M2           track        M2               nil nil t t nil )
  ( M2           grid         M2               t nil nil nil nil )
  ( M2           blockage     M2               t nil t t nil )
  ( M3           drawing      M3               t t nil nil t )
  ( M3           track        M3               nil nil t t nil )
  ( M3           grid         M3               t nil nil nil nil )
  ( M3           blockage     M3               t nil t t nil )
  ( M4           drawing      M4               t t nil nil t )
  ( M4           track        M4               nil nil t t nil )
  ( M4           grid         M4               t nil nil nil nil )
  ( M4           blockage     M4               t nil t t nil )
  ( M5           drawing      M5               t t nil nil t )
  ( M5           track        M5               nil nil t t nil )
  ( M5           grid         M5               t nil nil nil nil )
  ( M5           blockage     M5               t nil t t nil )
  ( M6           drawing      M6               t t nil nil t )
  ( M6           track        M6               nil nil t t nil )
  ( M6           grid         M6               t nil nil nil nil )
  ( M6           blockage     M6               t nil t t nil )
  ( M7           drawing      M7               t t nil nil t )
  ( M7           track        M7               nil nil t t nil )
  ( M7           grid         M7               t nil nil nil nil )
  ( M7           blockage     M7               t nil t t nil )
  ( M8           drawing      M8               t t nil nil t )
  ( M8           track        M8               nil nil t t nil )
  ( M8           grid         M8               t nil nil nil nil )
  ( M8           blockage     M8               t nil t t nil )
  ( RRAM         drawing      RRAM             t t nil nil t )
  ( RRAM         track        RRAM             nil nil t t nil )
  ( RRAM         grid         RRAM             t nil nil nil nil )
  ( RRAM         blockage     RRAM             t nil t t nil )
  ( M9           drawing      M9               t t nil nil t )
  ( M9           track        M9               nil nil t t nil )
  ( M9           grid         M9               t nil nil nil nil )
  ( M9           blockage     M9               t nil t t nil )
  ( NEMCONT      drawing      NEMCONT          t t nil nil t )
  ( NEMCONT      track        NEMCONT          nil nil t t nil )
  ( NEMCONT      grid         NEMCONT          t nil nil nil nil )
  ( NEMCONT      blockage     NEMCONT          t nil t t nil )
  ( NEMDIMP      drawing      NEMDIMP          t t nil nil t )
  ( NEMDIMP      track        NEMDIMP          nil nil t t nil )
  ( NEMDIMP      grid         NEMDIMP          t nil nil nil nil )
  ( NEMDIMP      blockage     NEMDIMP          t nil t t nil )
  ( NEMANC       drawing      NEMANC           t t nil nil t )
  ( NEMANC       track        NEMANC           nil nil t t nil )
  ( NEMANC       grid         NEMANC           t nil nil nil nil )
  ( NEMANC       blockage     NEMANC           t nil t t nil )
  ( NEMCHAN      drawing      NEMCHAN          t t nil nil t )
  ( NEMCHAN      track        NEMCHAN          nil nil t t nil )
  ( NEMCHAN      grid         NEMCHAN          t nil nil nil nil )
  ( NEMCHAN      blockage     NEMCHAN          t nil t t nil )
  ( NEMBEAM      drawing      NEMBEAM          t t nil nil t )
  ( NEMBEAM      track        NEMBEAM          nil nil t t nil )
  ( NEMBEAM      grid         NEMBEAM          t nil nil nil nil )
  ( NEMBEAM      blockage     NEMBEAM          t nil t t nil )
  ( CO           drawing      CO               t t nil nil t )
  ( CO           grid         CO               t nil nil nil nil )
  ( CO           blockage     CO               t nil t t nil )
  ( VIA1         drawing      VIA1             t t nil nil t )
  ( VIA1         grid         VIA1             t nil nil nil nil )
  ( VIA1         blockage     VIA1             t nil t t nil )
  ( VIA2         drawing      VIA2             t t nil nil t )
  ( VIA2         grid         VIA2             t nil nil nil nil )
  ( VIA2         blockage     VIA2             t nil t t nil )
  ( VIA3         drawing      VIA3             t t nil nil t )
  ( VIA3         grid         VIA3             t nil nil nil nil )
  ( VIA3         blockage     VIA3             t nil t t nil )
  ( VIA4         drawing      VIA4             t t nil nil t )
  ( VIA4         grid         VIA4             t nil nil nil nil )
  ( VIA4         blockage     VIA4             t nil t t nil )
  ( VIA5         drawing      VIA5             t t nil nil t )
  ( VIA5         grid         VIA5             t nil nil nil nil )
  ( VIA5         blockage     VIA5             t nil t t nil )
  ( VIA6         drawing      VIA6             t t nil nil t )
  ( VIA6         grid         VIA6             t nil nil nil nil )
  ( VIA6         blockage     VIA6             t nil t t nil )
  ( VIA7         drawing      VIA7             t t nil nil t )
  ( VIA7         grid         VIA7             t nil nil nil nil )
  ( VIA7         blockage     VIA7             t nil t t nil )
  ( VIA8         drawing      VIA8             t t nil nil t )
  ( VIA8         grid         VIA8             t nil nil nil nil )
  ( VIA8         blockage     VIA8             t nil t t nil )
  ( HVTIMP       drawing      HVTIMP           t t nil nil t )
  ( LVTIMP       drawing      LVTIMP           t t nil nil t )
  ( M1           text         M1PIN            t t nil nil t )
  ( M2           text         M2PIN            t t nil nil t )
  ( M3           text         M3PIN            t t nil nil t )
  ( M4           text         M4PIN            t t nil nil t )
  ( M5           text         M5PIN            t t nil nil t )
  ( M6           text         M6PIN            t t nil nil t )
  ( M7           text         M7PIN            t t nil nil t )
  ( M8           text         M8PIN            t t nil nil t )
  ( M9           text         M9PIN            t t nil nil t )
  ( M1PIN        drawing      M1PIN            t t nil nil t )
  ( M2PIN        drawing      M2PIN            t t nil nil t )
  ( M3PIN        drawing      M3PIN            t t nil nil t )
  ( M4PIN        drawing      M4PIN            t t nil nil t )
  ( M5PIN        drawing      M5PIN            t t nil nil t )
  ( M6PIN        drawing      M6PIN            t t nil nil t )
  ( M7PIN        drawing      M7PIN            t t nil nil t )
  ( M8PIN        drawing      M8PIN            t t nil nil t )
  ( M9PIN        drawing      M9PIN            t t nil nil t )
  ( MRDL         drawing      MRDL             t t nil nil t )
  ( MRDL         track        MRDL             nil nil t t nil )
  ( MRDL         grid         MRDL             t nil nil nil nil )
  ( MRDL         blockage     MRDL             t nil t t nil )
  ( VIARDL       drawing      VIARDL           t t nil nil t )
  ( VIARDL       grid         VIARDL           t nil nil nil nil )
  ( VIARDL       blockage     VIARDL           t nil t t nil )
  ( MRPIN        drawing      MRPIN            t t nil nil t )
  ( HOTNWL       drawing      HOTNWL           t t nil nil t )
  ( DIOD         drawing      DIOD             t t nil nil t )
  ( BJTMY        drawing      BJTMY            t t nil nil t )
  ( RNW          drawing      RNW              t t nil nil t )
  ( RMARK        drawing      RMARK            t t nil nil t )
  ( LOGO         drawing      LOGO             t t nil nil t )
  ( IP           drawing      IP               t t nil nil t )
  ( PrBoundary   drawing      PrBoundary       t t nil nil t )
  ( RM1          drawing      RM1              t t nil nil t )
  ( RM2          drawing      RM2              t t nil nil t )
  ( RM3          drawing      RM3              t t nil nil t )
  ( RM4          drawing      RM4              t t nil nil t )
  ( RM5          drawing      RM5              t t nil nil t )
  ( RM6          drawing      RM6              t t nil nil t )
  ( RM7          drawing      RM7              t t nil nil t )
  ( RM8          drawing      RM8              t t nil nil t )
  ( RM9          drawing      RM9              t t nil nil t )
  ( DM1EXCL      drawing      DM1EXCL          t t nil nil t )
  ( DM2EXCL      drawing      DM2EXCL          t t nil nil t )
  ( DM3EXCL      drawing      DM3EXCL          t t nil nil t )
  ( DM4EXCL      drawing      DM4EXCL          t t nil nil t )
  ( DM5EXCL      drawing      DM5EXCL          t t nil nil t )
  ( DM6EXCL      drawing      DM6EXCL          t t nil nil t )
  ( DM7EXCL      drawing      DM7EXCL          t t nil nil t )
  ( DM8EXCL      drawing      DM8EXCL          t t nil nil t )
  ( DM9EXCL      drawing      DM9EXCL          t t nil nil t )
  ( DIFFEXCL     drawing      DIFFEXCL         t t nil nil t )
  ( POEXCL       drawing      POEXCL           t t nil nil t )
  ( DIFF_25      drawing      DIFF_25          t t nil nil t )
  ( CBMMARK      drawing      CBMMARK          t t nil nil t )
  ( CTMMARK      drawing      CTMMARK          t t nil nil t )
  ( METDMY       drawing      METDMY           t t nil nil t )
 ) ;techDisplays

 techLayerProperties(
 ;( PropName               Layer1 [ Layer2 ]            PropValue )
 ;( --------               ------ ----------            --------- )
  ( sheetResistance        DIFF                           0.001000 )
  ( sheetResistance        PO                             15 )
  ( sheetResistance        M1                             0.100000 )
  ( resistancePerCut       VIA1                           1.500000 )
  ( sheetResistance        M2                             0.100000 )
  ( resistancePerCut       VIA2                           1.500000 )
  ( sheetResistance        M3                             0.100000 )
  ( resistancePerCut       VIA3                           1.500000 )
  ( sheetResistance        M4                             0.100000 )
  ( resistancePerCut       VIA4                           1.500000 )
  ( sheetResistance        M5                             0.100000 )
  ( resistancePerCut       VIA5                           1.500000 )
  ( sheetResistance        M6                             0.100000 )
  ( resistancePerCut       VIA6                           1.500000 )
  ( sheetResistance        M7                             0.100000 )
  ( resistancePerCut       VIA7                           1.500000 )
  ( sheetResistance        M8                             0.100000 )
  ( resistancePerCut       VIA8                           0.100000 )
  ( sheetResistance        RRAM                           0.125000 )
  ( sheetResistance        M9                             0.280000 )
  ( sheetResistance        NEMCONT                        0.280000 )
  ( sheetResistance        NEMDIMP                        0.280000 )
  ( sheetResistance        NEMANC                         15 )
  ( sheetResistance        NEMCHAN                        0.280000 )
  ( sheetResistance        NEMBEAM                        15       )
  ( sheetResistance        MRDL                           0.350000 )
  ( resistancePerCut       VIARDL                         0.050000 )
 ) ;techLayerProperties

) ;layerDefinitions


;********************************
; LAYER RULES
;********************************
layerRules(

 functions(
 ;( layer                       function        [maskNumber])
 ;( -----                       --------        ------------)
  ( NWELL                    	"nwell"     	1            )
  ( DIFF                     	"diff"      	2            )
  ( DIFF_18                  	"diff"      	3            )
  ( DIFF_25                  	"diff"      	4            )
  ( PIMP                     	"pplus"     	5            )
  ( NIMP                     	"nplus"     	6            )
  ( M1                       	"metal"     	7            )
  ( VIA1                     	"cut"       	8            )
  ( M2                       	"metal"     	9            )
  ( VIA2                     	"cut"       	10           )
  ( M3                       	"metal"     	11           )
  ( VIA3                     	"cut"       	12           )
  ( M4                       	"metal"     	13           )
  ( VIA4                     	"cut"       	14           )
  ( M5                       	"metal"     	15           )
  ( VIA5                     	"cut"       	16           )
  ( M6                       	"metal"     	17           )
  ( VIA6                     	"cut"       	18           )
  ( M7                       	"metal"     	19           )
  ( M8                       	"metal"     	20           )
  ( RRAM                     	"metal"     	74           )
  ( M9                       	"metal"     	21           )
  ( MRDL                     	"metal"     	22           )
  ( VIARDL                   	"cut"       	23           )
  ( VIA7                     	"cut"       	24           )
  ( VIA8                     	"cut"       	25           )
  ( CO                       	"cut"       	26           )
  ( NEMCONT                   "unknown"   	75           )
  ( NEMDIMP                   "unknown"   	76           )
  ( NEMANC                    "unknown"   	77           )
  ( NEMCHAN                   "unknown"   	78           )
  ( NEMBEAM                   "unknown"   	79           )
  ( BJTMY                    	"unknown"   	27           )
  ( DIOD                     	"unknown"   	28           )
  ( DM1EXCL                  	"unknown"   	29           )
  ( DM2EXCL                  	"unknown"   	30           )
  ( DM3EXCL                  	"unknown"   	31           )
  ( DM4EXCL                  	"unknown"   	32           )
  ( DM5EXCL                  	"unknown"   	33           )
  ( DM6EXCL                  	"unknown"   	34           )
  ( DM7EXCL                  	"unknown"   	35           )
  ( DM8EXCL                  	"unknown"   	36           )
  ( DM9EXCL                  	"unknown"   	37           )
  ( DNW                      	"unknown"   	38           )
  ( ESD_25                   	"unknown"   	39           )
  ( HOTNWL                   	"unknown"   	40           )
  ( HVTIMP                   	"unknown"   	41           )
  ( IP                       	"unknown"   	42           )
  ( LOGO                     	"unknown"   	43           )
  ( LVTIMP                   	"unknown"   	44           )
  ( M1PIN                    	"unknown"   	45           )
  ( M2PIN                    	"unknown"   	46           )
  ( M3PIN                    	"unknown"   	47           )
  ( M4PIN                    	"unknown"   	48           )
  ( M5PIN                    	"unknown"   	49           )
  ( M6PIN                    	"unknown"   	50           )
  ( M7PIN                    	"unknown"   	51           )
  ( M8PIN                    	"unknown"   	52           )
  ( M9PIN                    	"unknown"   	53           )
  ( MRPIN                    	"unknown"   	54           )
  ( PAD                      	"unknown"   	55           )
  ( PO                       	"unknown"   	56           )
  ( RM1                      	"unknown"   	57           )
  ( RM2                      	"unknown"   	58           )
  ( RM3                      	"unknown"   	59           )
  ( RM4                      	"unknown"   	60           )
  ( RM5                      	"unknown"   	61           )
  ( RM6                      	"unknown"   	62           )
  ( RM7                      	"unknown"   	63           )
  ( RM8                      	"unknown"   	64           )
  ( RM9                      	"unknown"   	65           )
  ( RNW                      	"unknown"   	66           )
  ( RMARK                    	"unknown"   	67           )
  ( SBLK                     	"unknown"   	69           )
  ( PrBoundary               	"unknown"   	70           )
  ( CBMMARK                  	"unknown"   	71           )
  ( CTMMARK                  	"unknown"   	72           )
  ( METDMY                   	"unknown"   	73           )
 ) ;functions

 routingDirections(
 ;( layer                       direction     )
 ;( -----                       ---------     )
  ( M1                       	"horizontal" )
  ( M2                       	"vertical"   )
  ( M3                       	"horizontal" )
  ( M4                       	"vertical"   )
  ( M5                       	"horizontal" )
  ( M6                       	"vertical"   )
  ( M7                       	"horizontal" )
  ( M8                       	"vertical"   )
  ( M9                       	"horizontal" )
  ( MRDL                     	"vertical"   )
 ) ;routingDirections

) ;layerRules


;********************************
; VIADEFS
;********************************
viaDefs(

 standardViaDefs(
 ;( viaDefName	layer1	layer2	(cutLayer cutWidth cutHeight [resistancePerCut]) 
 ;   (cutRows	cutCol	(cutSpace)	[(l_cutPattern)]) 
 ;   (layer1Enc) (layer2Enc)	(layer1Offset)	(layer2Offset)	(origOffset) 
 ;   [implant1	 (implant1Enc)	[implant2	(implant2Enc) [well/substrate]]]) 
 ;( -------------------------------------------------------------------------- ) 
  ( DIFFCON     	DIFF        M1          	("CO" 0.042 0.042)
     (1 1 (0.05 0.05))
     (0.02 0.01)	(0.035 0.004)	(0.0 0.0)	(0.0 0.0)	(0.0 0.0)
  )
  ( DIFFCONC    	DIFF        M1          	("CO" 0.042 0.042)
     (1 1 (0.05 0.05))
     (0.01 0.02)	(0.035 0.004)	(0.0 0.0)	(0.0 0.0)	(0.0 0.0)
  )
  ( POLYCON1    	PO          M1          	("CO" 0.042 0.042)
     (1 1 (0.05 0.05))
     (0.05 0.02)	(0.035 0.004)	(0.0 0.0)	(0.0 0.0)	(0.0 0.0)
  )
  ( POLYCON1C   	PO          M1          	("CO" 0.042 0.042)
     (1 1 (0.05 0.05))
     (0.02 0.05)	(0.035 0.004)	(0.0 0.0)	(0.0 0.0)	(0.0 0.0)
  )
  ( POLYCON2    	PO          M1          	("CO" 0.042 0.042)
     (1 1 (0.05 0.05))
     (0.034 0.02)	(0.035 0.004)	(0.0 0.0)	(0.0 0.0)	(0.0 0.0)
  )
  ( POLYCON2C   	PO          M1          	("CO" 0.042 0.042)
     (1 1 (0.05 0.05))
     (0.02 0.034)	(0.035 0.004)	(0.0 0.0)	(0.0 0.0)	(0.0 0.0)
  )
  ( VIA12       	M1          M2          	("VIA1" 0.05 0.05 1.5)
     (1 1 (0.07 0.07))
     (0.03 0.005)	(0.03 0.005)	(0.0 0.0)	(0.0 0.0)	(0.0 0.0)
  )
  ( VIA12C      	M1          M2          	("VIA1" 0.05 0.05 1.5)
     (1 1 (0.07 0.07))
     (0.005 0.03)	(0.03 0.005)	(0.0 0.0)	(0.0 0.0)	(0.0 0.0)
  )
  ( VIA12BAR    	M1          M2          	("VIA1" 0.05 0.1 1.0)
     (1 1 (0.085 0.085))
     (0.03 0.005)	(0.03 0.005)	(0.0 0.0)	(0.0 0.0)	(0.0 0.0)
  )
  ( VIA12BARC   	M1          M2          	("VIA1" 0.05 0.1 1.0)
     (1 1 (0.085 0.085))
     (0.005 0.03)	(0.03 0.005)	(0.0 0.0)	(0.0 0.0)	(0.0 0.0)
  )
  ( VIA12LG     	M1          M2          	("VIA1" 0.1 0.1 0.5)
     (1 1 (0.085 0.085))
     (0.03 0.005)	(0.03 0.005)	(0.0 0.0)	(0.0 0.0)	(0.0 0.0)
  )
  ( VIA12LGC    	M1          M2          	("VIA1" 0.1 0.1 0.5)
     (1 1 (0.085 0.085))
     (0.005 0.03)	(0.03 0.005)	(0.0 0.0)	(0.0 0.0)	(0.0 0.0)
  )
  ( VIA23       	M2          M3          	("VIA2" 0.05 0.05 1.5)
     (1 1 (0.07 0.07))
     (0.03 0.005)	(0.03 0.005)	(0.0 0.0)	(0.0 0.0)	(0.0 0.0)
  )
  ( VIA23C      	M2          M3          	("VIA2" 0.05 0.05 1.5)
     (1 1 (0.07 0.07))
     (0.005 0.03)	(0.03 0.005)	(0.0 0.0)	(0.0 0.0)	(0.0 0.0)
  )
  ( VIA23BAR    	M2          M3          	("VIA2" 0.05 0.1 1.0)
     (1 1 (0.085 0.085))
     (0.03 0.005)	(0.03 0.005)	(0.0 0.0)	(0.0 0.0)	(0.0 0.0)
  )
  ( VIA23BARC   	M2          M3          	("VIA2" 0.05 0.1 1.0)
     (1 1 (0.085 0.085))
     (0.005 0.03)	(0.03 0.005)	(0.0 0.0)	(0.0 0.0)	(0.0 0.0)
  )
  ( VIA23LG     	M2          M3          	("VIA2" 0.1 0.1 0.5)
     (1 1 (0.085 0.085))
     (0.03 0.005)	(0.03 0.005)	(0.0 0.0)	(0.0 0.0)	(0.0 0.0)
  )
  ( VIA23LGC    	M2          M3          	("VIA2" 0.1 0.1 0.5)
     (1 1 (0.085 0.085))
     (0.005 0.03)	(0.03 0.005)	(0.0 0.0)	(0.0 0.0)	(0.0 0.0)
  )
  ( VIA34       	M3          M4          	("VIA3" 0.05 0.05 1.5)
     (1 1 (0.07 0.07))
     (0.03 0.005)	(0.03 0.005)	(0.0 0.0)	(0.0 0.0)	(0.0 0.0)
  )
  ( VIA34C      	M3          M4          	("VIA3" 0.05 0.05 1.5)
     (1 1 (0.07 0.07))
     (0.005 0.03)	(0.03 0.005)	(0.0 0.0)	(0.0 0.0)	(0.0 0.0)
  )
  ( VIA34BAR    	M3          M4          	("VIA3" 0.05 0.1 1.0)
     (1 1 (0.085 0.085))
     (0.03 0.005)	(0.03 0.005)	(0.0 0.0)	(0.0 0.0)	(0.0 0.0)
  )
  ( VIA34BARC   	M3          M4          	("VIA3" 0.05 0.1 1.0)
     (1 1 (0.085 0.085))
     (0.005 0.03)	(0.03 0.005)	(0.0 0.0)	(0.0 0.0)	(0.0 0.0)
  )
  ( VIA34LG     	M3          M4          	("VIA3" 0.1 0.1 0.5)
     (1 1 (0.085 0.085))
     (0.03 0.005)	(0.03 0.005)	(0.0 0.0)	(0.0 0.0)	(0.0 0.0)
  )
  ( VIA34LGC    	M3          M4          	("VIA3" 0.1 0.1 0.5)
     (1 1 (0.085 0.085))
     (0.005 0.03)	(0.03 0.005)	(0.0 0.0)	(0.0 0.0)	(0.0 0.0)
  )
  ( VIA45       	M4          M5          	("VIA4" 0.05 0.05 1.5)
     (1 1 (0.07 0.07))
     (0.03 0.005)	(0.03 0.005)	(0.0 0.0)	(0.0 0.0)	(0.0 0.0)
  )
  ( VIA45C      	M4          M5          	("VIA4" 0.05 0.05 1.5)
     (1 1 (0.07 0.07))
     (0.005 0.03)	(0.03 0.005)	(0.0 0.0)	(0.0 0.0)	(0.0 0.0)
  )
  ( VIA45BAR    	M4          M5          	("VIA4" 0.05 0.1 1.0)
     (1 1 (0.085 0.085))
     (0.03 0.005)	(0.03 0.005)	(0.0 0.0)	(0.0 0.0)	(0.0 0.0)
  )
  ( VIA45BARC   	M4          M5          	("VIA4" 0.05 0.1 1.0)
     (1 1 (0.085 0.085))
     (0.005 0.03)	(0.03 0.005)	(0.0 0.0)	(0.0 0.0)	(0.0 0.0)
  )
  ( VIA45LG     	M4          M5          	("VIA4" 0.1 0.1 0.5)
     (1 1 (0.085 0.085))
     (0.03 0.005)	(0.03 0.005)	(0.0 0.0)	(0.0 0.0)	(0.0 0.0)
  )
  ( VIA45LGC    	M4          M5          	("VIA4" 0.1 0.1 0.5)
     (1 1 (0.085 0.085))
     (0.005 0.03)	(0.03 0.005)	(0.0 0.0)	(0.0 0.0)	(0.0 0.0)
  )
  ( VIA56       	M5          M6          	("VIA5" 0.05 0.05 1.5)
     (1 1 (0.07 0.07))
     (0.03 0.005)	(0.03 0.005)	(0.0 0.0)	(0.0 0.0)	(0.0 0.0)
  )
  ( VIA56C      	M5          M6          	("VIA5" 0.05 0.05 1.5)
     (1 1 (0.07 0.07))
     (0.005 0.03)	(0.03 0.005)	(0.0 0.0)	(0.0 0.0)	(0.0 0.0)
  )
  ( VIA56BAR    	M5          M6          	("VIA5" 0.05 0.1 1.0)
     (1 1 (0.085 0.085))
     (0.03 0.005)	(0.03 0.005)	(0.0 0.0)	(0.0 0.0)	(0.0 0.0)
  )
  ( VIA56BARC   	M5          M6          	("VIA5" 0.05 0.1 1.0)
     (1 1 (0.085 0.085))
     (0.005 0.03)	(0.03 0.005)	(0.0 0.0)	(0.0 0.0)	(0.0 0.0)
  )
  ( VIA56LG     	M5          M6          	("VIA5" 0.1 0.1 0.5)
     (1 1 (0.085 0.085))
     (0.03 0.005)	(0.03 0.005)	(0.0 0.0)	(0.0 0.0)	(0.0 0.0)
  )
  ( VIA56LGC    	M5          M6          	("VIA5" 0.1 0.1 0.5)
     (1 1 (0.085 0.085))
     (0.005 0.03)	(0.03 0.005)	(0.0 0.0)	(0.0 0.0)	(0.0 0.0)
  )
  ( VIA67       	M6          M7          	("VIA6" 0.05 0.05 1.5)
     (1 1 (0.07 0.07))
     (0.03 0.005)	(0.03 0.005)	(0.0 0.0)	(0.0 0.0)	(0.0 0.0)
  )
  ( VIA67C      	M6          M7          	("VIA6" 0.05 0.05 1.5)
     (1 1 (0.07 0.07))
     (0.005 0.03)	(0.03 0.005)	(0.0 0.0)	(0.0 0.0)	(0.0 0.0)
  )
  ( VIA67BAR    	M6          M7          	("VIA6" 0.05 0.1 1.0)
     (1 1 (0.085 0.085))
     (0.03 0.005)	(0.03 0.005)	(0.0 0.0)	(0.0 0.0)	(0.0 0.0)
  )
  ( VIA67BARC   	M6          M7          	("VIA6" 0.05 0.1 1.0)
     (1 1 (0.085 0.085))
     (0.005 0.03)	(0.03 0.005)	(0.0 0.0)	(0.0 0.0)	(0.0 0.0)
  )
  ( VIA67LG     	M6          M7          	("VIA6" 0.1 0.1 0.5)
     (1 1 (0.085 0.085))
     (0.03 0.005)	(0.03 0.005)	(0.0 0.0)	(0.0 0.0)	(0.0 0.0)
  )
  ( VIA67LGC    	M6          M7          	("VIA6" 0.1 0.1 0.5)
     (1 1 (0.085 0.085))
     (0.005 0.03)	(0.03 0.005)	(0.0 0.0)	(0.0 0.0)	(0.0 0.0)
  )
  ( VIA78       	M7          M8          	("VIA7" 0.05 0.05 1.5)
     (1 1 (0.07 0.07))
     (0.03 0.005)	(0.03 0.005)	(0.0 0.0)	(0.0 0.0)	(0.0 0.0)
  )
  ( VIA78C      	M7          M8          	("VIA7" 0.05 0.05 1.5)
     (1 1 (0.07 0.07))
     (0.005 0.03)	(0.03 0.005)	(0.0 0.0)	(0.0 0.0)	(0.0 0.0)
  )
  ( VIA78BAR    	M7          M8          	("VIA7" 0.05 0.1 1.0)
     (1 1 (0.085 0.085))
     (0.03 0.005)	(0.03 0.005)	(0.0 0.0)	(0.0 0.0)	(0.0 0.0)
  )
  ( VIA78BARC   	M7          M8          	("VIA7" 0.05 0.1 1.0)
     (1 1 (0.085 0.085))
     (0.005 0.03)	(0.03 0.005)	(0.0 0.0)	(0.0 0.0)	(0.0 0.0)
  )
  ( VIA78LG     	M7          M8          	("VIA7" 0.1 0.1 0.5)
     (1 1 (0.085 0.085))
     (0.03 0.005)	(0.03 0.005)	(0.0 0.0)	(0.0 0.0)	(0.0 0.0)
  )
  ( VIA78LGC    	M7          M8          	("VIA7" 0.1 0.1 0.5)
     (1 1 (0.085 0.085))
     (0.005 0.03)	(0.03 0.005)	(0.0 0.0)	(0.0 0.0)	(0.0 0.0)
  )
  ( VIA89       	M8          M9          	("VIA8" 0.13 0.13 0.1)
     (1 1 (0.12 0.12))
     (0.03 0.015)	(0.03 0.015)	(0.0 0.0)	(0.0 0.0)	(0.0 0.0)
  )
  ( VIA89C      	M8          M9          	("VIA8" 0.13 0.13 0.1)
     (1 1 (0.12 0.12))
     (0.015 0.03)	(0.03 0.015)	(0.0 0.0)	(0.0 0.0)	(0.0 0.0)
  )
  ( VIARDL      	M9          MRDL        	("VIARDL" 2.0 2.0 0.05)
     (1 1 (2.0 2.0))
     (0.05 0.05)	(0.05 0.05)	(0.0 0.0)	(0.0 0.0)	(0.0 0.0)
  )
 ) ;standardViaDefs

) ;viaDefs



;********************************
; CONSTRAINT GROUPS
;********************************
constraintGroups(

 ;( group	[override]	[definition]	[operator] )
 ;( -----	----------	------------	---------- )
  ( "leCEConstraintGroup"	nil

    interconnect(
     ( validLayers   (VIARDL  VIA8  VIA7  VIA6  VIA5  VIA4  VIA3  VIA2  VIA1  MRDL  NEMCONT  NEMDIMP  NEMCHAN  NEMANC  NEMBEAM  M9  RRAM  M8  M7  M6  M5  M4  M3  M2  M1  CO  PO  DIFF  ) )
     ( validVias     (DIFFCON  DIFFCONC  POLYCON1  POLYCON1C  POLYCON2  POLYCON2C  VIA12  VIA12C  VIA12BAR  VIA12BARC  VIA12LG  VIA12LGC  VIA23  VIA23C  VIA23BAR  VIA23BARC  VIA23LG  VIA23LGC  VIA34  VIA34C  VIA34BAR  VIA34BARC  VIA34LG  VIA34LGC  VIA45  VIA45C  VIA45BAR  VIA45BARC  VIA45LG  VIA45LGC  VIA56  VIA56C  VIA56BAR  VIA56BARC  VIA56LG  VIA56LGC  VIA67  VIA67C  VIA67BAR  VIA67BARC  VIA67LG  VIA67LGC  VIA78  VIA78C  VIA78BAR  VIA78BARC  VIA78LG  VIA78LGC  VIA89  VIA89C  VIARDL  ) )
    ) ;interconnect
  ) ;leCEConstraintGroup

 ;( group	[override]	[definition]	[operator] )
 ;( -----	----------	------------	---------- )
  ( "LEFDefaultRouteSpec"	nil

    spacings(
     ( minWidth                   "CO"	0.042 )
    ) ;spacings

    routingGrids(
     ( horizontalPitch            "M1"	0.2 )
     ( verticalPitch              "M1"	0.2 )
     ( horizontalOffset           "M1"	0.1 )
     ( verticalOffset             "M1"	0.1 )
    ) ;routingGrids

    spacings(
     ( minWidth                   "M1"	0.05 )
     ( minWireExtension           "M1"	0.105 )
     ( minWidth                   "VIA1"	0.05 )
    ) ;spacings

    routingGrids(
     ( horizontalPitch            "M2"	0.3 )
     ( verticalPitch              "M2"	0.3 )
     ( horizontalOffset           "M2"	0.15 )
     ( verticalOffset             "M2"	0.15 )
    ) ;routingGrids

    spacings(
     ( minWidth                   "M2"	0.056 )
     ( minWireExtension           "M2"	0.105 )
     ( minWidth                   "VIA2"	0.05 )
    ) ;spacings

    routingGrids(
     ( horizontalPitch            "M3"	0.3 )
     ( verticalPitch              "M3"	0.3 )
     ( horizontalOffset           "M3"	0.15 )
     ( verticalOffset             "M3"	0.15 )
    ) ;routingGrids

    spacings(
     ( minWidth                   "M3"	0.056 )
     ( minWireExtension           "M3"	0.105 )
     ( minWidth                   "VIA3"	0.05 )
    ) ;spacings

    routingGrids(
     ( horizontalPitch            "M4"	0.3 )
     ( verticalPitch              "M4"	0.3 )
     ( horizontalOffset           "M4"	0.15 )
     ( verticalOffset             "M4"	0.15 )
    ) ;routingGrids

    spacings(
     ( minWidth                   "M4"	0.056 )
     ( minWireExtension           "M4"	0.105 )
    ) ;spacings

    interconnect(
     ( validLayers   (PO  M1  M2  M3  M4  M5  M6  M7  M8  RRAM  M9  NEMCONT  NEMDIMP  NEMANC  NEMCHAN  NEMBEAM  MRDL  ) )
     ( validVias     (VIA12  VIA12BAR  VIA12LG  VIA12C  VIA12BARC  VIA12LGC  VIA23  VIA23BAR  VIA23LG  VIA23C  VIA23BARC  VIA23LGC  VIA34  VIA34BAR  VIA34LG  VIA34C  VIA34BARC  VIA34LGC  POLYCON1  POLYCON1C  POLYCON2  POLYCON2C  DIFFCON  VIA45  VIA45BAR  VIA45LG  VIA56  VIA56BAR  VIA56LG  VIA67  VIA67BAR  VIA67LG  VIA78  VIA78BAR  VIA78LG  VIA89  ) )
    ) ;interconnect
  ) ;LEFDefaultRouteSpec

 ;( group	[override]	[definition]	[operator] )
 ;( -----	----------	------------	---------- )
  ( "foundry"	nil

    spacings(
     ( minWidth                   "NWELL"	0.23 )
     ( minSpacing                 "NWELL"	0.23 )
     ( minDiffNetSpacing          "NWELL"	0.46 )
     ( minArea                    "NWELL"	0.45 )
     ( minHoleArea                "NWELL"	0.45 )
     ( minSpacing                 "DNW"	3.5 )
     ( minWidth                   "DNW"	3.0 )
     ( minWidth                   "DIFF"	0.044 )
     ( minSpacing                 "DIFF"	0.05 )
     ( minArea                    "DIFF"	0.02 )
     ( minHoleArea                "DIFF"	0.03 )
     ( minWidth                   "DIFF_18"	0.33 )
     ( minSpacing                 "DIFF_18"	0.33 )
     ( minArea                    "DIFF_18"	0.4 )
     ( minHoleArea                "DIFF_18"	0.4 )
     ( minWidth                   "PO"	0.03 )
     ( minSpacing                 "PO"	0.086 )
     ( minArea                    "PO"	0.012 )
     ( minWidth                   "PIMP"	0.102 )
     ( minSpacing                 "PIMP"	0.17 )
     ( minWidth                   "NIMP"	0.102 )
     ( minSpacing                 "NIMP"	0.17 )
     ( minWidth                   "CO"	0.042 )
     ( maxLength                  "CO"	0.042 )
     ( maxWidth                   "CO"	0.042 )
     ( minSpacing                 "CO"	0.05 )
     ( minWidth                   "M1"	0.05 )
     ( maxWidth                   "M1"	5.0 )
     ( minSpacing                 "M1"	0.05 )
     ( minArea                    "M1"	0.01 )
     ( minHoleArea                "M1"	0.2 )
     ( minWidth                   "VIA1"	0.05 )
     ( maxLength                  "VIA1"	0.1 )
     ( maxWidth                   "VIA1"	0.1 )
     ( minSpacing                 "VIA1"	0.07 )
     ( minWidth                   "M2"	0.056 )
     ( maxWidth                   "M2"	5.0 )
     ( minSpacing                 "M2"	0.056 )
     ( minArea                    "M2"	0.016 )
     ( minHoleArea                "M2"	0.2 )
     ( minWidth                   "VIA2"	0.05 )
     ( maxLength                  "VIA2"	0.1 )
     ( maxWidth                   "VIA2"	0.1 )
     ( minSpacing                 "VIA2"	0.07 )
     ( minWidth                   "M3"	0.056 )
     ( maxWidth                   "M3"	5.0 )
     ( minSpacing                 "M3"	0.056 )
     ( minArea                    "M3"	0.016 )
     ( minHoleArea                "M3"	0.2 )
     ( minWidth                   "VIA3"	0.05 )
     ( maxLength                  "VIA3"	0.1 )
     ( maxWidth                   "VIA3"	0.1 )
     ( minSpacing                 "VIA3"	0.07 )
     ( minWidth                   "M4"	0.056 )
     ( maxWidth                   "M4"	5.0 )
     ( minSpacing                 "M4"	0.056 )
     ( minArea                    "M4"	0.016 )
     ( minHoleArea                "M4"	0.2 )
     ( minWidth                   "VIA4"	0.05 )
     ( maxLength                  "VIA4"	0.1 )
     ( maxWidth                   "VIA4"	0.1 )
     ( minSpacing                 "VIA4"	0.07 )
     ( minWidth                   "M5"	0.056 )
     ( maxWidth                   "M5"	5.0 )
     ( minSpacing                 "M5"	0.056 )
     ( minArea                    "M5"	0.016 )
     ( minHoleArea                "M5"	0.2 )
     ( minWidth                   "VIA5"	0.05 )
     ( maxLength                  "VIA5"	0.1 )
     ( maxWidth                   "VIA5"	0.1 )
     ( minSpacing                 "VIA5"	0.07 )
     ( minWidth                   "M6"	0.056 )
     ( maxWidth                   "M6"	5.0 )
     ( minSpacing                 "M6"	0.056 )
     ( minArea                    "M6"	0.016 )
     ( minHoleArea                "M6"	0.2 )
     ( minWidth                   "VIA6"	0.05 )
     ( maxLength                  "VIA6"	0.1 )
     ( maxWidth                   "VIA6"	0.1 )
     ( minSpacing                 "VIA6"	0.07 )
     ( minWidth                   "M7"	0.056 )
     ( maxWidth                   "M7"	5.0 )
     ( minSpacing                 "M7"	0.056 )
     ( minArea                    "M7"	0.016 )
     ( minHoleArea                "M7"	0.2 )
     ( minWidth                   "VIA7"	0.05 )
     ( maxLength                  "VIA7"	0.1 )
     ( maxWidth                   "VIA7"	0.1 )
     ( minSpacing                 "VIA7"	0.07 )
     ( minWidth                   "M8"	0.056 )
     ( maxWidth                   "M8"	5.0 )
     ( minSpacing                 "M8"	0.056 )
     ( minArea                    "M8"	0.016 )
     ( minHoleArea                "M8"	0.2 )
     ( minWidth                   "RRAM"	0.056 )
     ( minSpacing                 "RRAM"	0.056 )
     ( minWidth                   "VIA8"	0.13 )
     ( maxLength                  "VIA8"	0.13 )
     ( maxWidth                   "VIA8"	0.13 )
     ( minSpacing                 "VIA8"	0.12 )
     ( minWidth                   "M9"	0.16 )
     ( maxWidth                   "M9"	10.0 )
     ( minSpacing                 "M9"	0.16 )
     ( minArea                    "M9"	0.055 )
     ( minHoleArea                "M9"	0.2 )
     ( minWidth                   "NEMCONT"	0.16 )
     ( maxWidth                   "NEMCONT"	10.0 )
     ( minSpacing                 "NEMCONT"	0.16 )
     ( minArea                    "NEMCONT"	0.055 )
     ( minWidth                   "NEMDIMP"	0.16 )
     ( maxWidth                   "NEMDIMP"	10.0 )
     ( minSpacing                 "NEMDIMP"	0.16 )
     ( minArea                    "NEMDIMP"	0.055 )
     ( minWidth                   "NEMCHAN"	0.16 )
     ( maxWidth                   "NEMCHAN"	10.0 )
     ( minSpacing                 "NEMCHAN"	0.16 )
     ( minArea                    "NEMCHAN"	0.055 )
     ( minWidth                   "NEMANC"	0.03 )
     ( minSpacing                 "NEMANC"	0.086 )
     ( minArea                    "NEMANC"	0.012 )
     ( minWidth                   "NEMBEAM"	0.03 )
     ( minSpacing                 "NEMBEAM"	0.086 )
     ( minArea                    "NEMBEAM"	0.012 )
     ( minWidth                   "MRDL"	2.0 )
     ( maxWidth                   "MRDL"	30.0 )
     ( minSpacing                 "MRDL"	2.0 )
     ( minWidth                   "VIARDL"	2.0 )
     ( maxLength                  "VIARDL"	2.0 )
     ( maxWidth                   "VIARDL"	2.0 )
     ( minSpacing                 "VIARDL"	2.0 )
     ( minWidth                   "HVTIMP"	0.85 )
     ( minSpacing                 "HVTIMP"	0.85 )
     ( minWidth                   "LVTIMP"	0.85 )
     ( minSpacing                 "LVTIMP"	0.85 )
     ( minWidth                   "SBLK"	0.33 )
     ( minSpacing                 "SBLK"	0.33 )
     ( minWidth                   "DIFF_25"	0.33 )
     ( minSpacing                 "DIFF_25"	0.33 )
     ( minArea                    "DIFF_25"	0.4 )
     ( minHoleArea                "DIFF_25"	0.4 )
     ( minSpacing                 "NWELL"	"DIFF"		0.065 )
     ( minSpacing                 "PIMP"	"DIFF"		0.02 )
     ( minSpacing                 "NIMP"	"DIFF"		0.02 )
     ( minSpacing                 "DIFF_18"	"DIFF"		0.15 )
     ( minSpacing                 "DIFF_25"	"DIFF"		0.15 )
     ( minSpacing                 "M1"	"VIA1"		0.08 )
     ( minSpacing                 "M2"	"VIA2"		0.08 )
     ( minSpacing                 "M3"	"VIA3"		0.08 )
     ( minSpacing                 "M4"	"VIA4"		0.08 )
     ( minSpacing                 "M5"	"VIA5"		0.08 )
     ( minSpacing                 "M6"	"VIA6"		0.08 )
     ( minSpacing                 "M7"	"VIA7"		0.08 )
     ( minSpacing                 "M8"	"VIA8"		0.08 )
     ( minSpacing                 "CO"	"PO"		0.04 )
     ( minSpacing                 "CO"	"DIFF"		0.04 )
     ( minSpacing                 "CO"	"SBLK"		0.13 )
     ( minSpacing                 "DIFF"	"PO"		0.02 )
     ( minSpacing                 "NIMP"	"PIMP"		0.0 )
    ) ;spacings

    spacings(
     ( minSpacing                 "NWELL"	"DNW"		2.5 )
     ( minSpacing                 "DNW"	"DIFF"		1.5 )
     ( minSpacing                 "SBLK"	"DIFF"		0.18 )
     ( minSpacing                 "SBLK"	"PO"		0.3 )
    ) ;spacings

    interconnect(
     ( validLayers   (CO  DIFF  DIFF_18  M1  M1PIN  M2  M2PIN  M3  M3PIN  M4  M4PIN  M5  M5PIN  M6  M6PIN  M7  M7PIN  M8  RRAM  M8PIN  M9  M9PIN  NEMCONT  NEMDIMP  NEMANC  NEMCHAN  NEMBEAM  MRDL  PO  VIA1  VIA2  VIA3  VIA4  VIA5  VIA6  VIA7  VIA8  VIARDL  ) )
    ) ;interconnect
  ) ;foundry
) ;constraintGroups
